# coding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if !User.exists?(email: Setting::User.admin.email )
  user=User.create(Setting::User.admin)
  user.super_admin = true
  user.save
  User.confirm_by_token(user.confirmation_token)
  puts "填充超级管理员数据"
end

if !User.exists?(email: Setting::User.test.email )
  user=User.create(Setting::User.test)
  User.confirm_by_token(user.confirmation_token)
  puts "填充测试账户数据"
end

if !User.exists?(email: Setting::User.zhangcaiyan.email )
  user=User.create(Setting::User.zhangcaiyan)
  User.confirm_by_token(user.confirmation_token)
  puts "填充zhangcaiyanbeyond账户数据"
end


if CompanyPriceCategory.first.nil? 
puts "开始填充企业报价相关的分类信息"
CompanyPriceCategory.delete_all
a = CompanyPriceCategory.create(name: "废塑料")
b = CompanyPriceCategory.create(name: "废金属")
c = CompanyPriceCategory.create(name: "废纸")
d = CompanyPriceCategory.create(name: "综合废料")

a_a = a.children.create(name: "废塑料")
a_a.children.create(name: "ABS")
a_a.children.create(name: "EVA")
a_a.children.create(name: "PA")
a_a.children.create(name: "PC")
a_a.children.create(name: "PE")
a_a.children.create(name: "PET")
a_a.children.create(name: "PP")
a_a.children.create(name: "PS")
a_a.children.create(name: "PVC")
a_a.children.create(name: "助剂")
a_a.children.create(name: "其它")

a_b = a.children.create(name: "塑料颗粒")
a_b.children.create(name: "ABS颗粒")
a_b.children.create(name: "EVA颗粒")
a_b.children.create(name: "PA颗粒")
a_b.children.create(name: "PC颗粒")
a_b.children.create(name: "PE颗粒")
a_b.children.create(name: "PET颗粒")
a_b.children.create(name: "PP颗粒")
a_b.children.create(name: "PS颗粒")
a_b.children.create(name: "PVC颗粒")
a_b.children.create(name: "其它颗粒")

b.children.create(name: "铁")
b.children.create(name: "铜")
b.children.create(name: "铝")
b.children.create(name: "铅")
b.children.create(name: "锌")
b.children.create(name: "锡")
b.children.create(name: "镍")
b.children.create(name: "其它")

c.children.create(name: "牛皮纸")
c.children.create(name: "瓦楞纸")
c.children.create(name: "淋膜纸")
c.children.create(name: "商标纸")
c.children.create(name: "利乐包")
c.children.create(name: "书刊")
c.children.create(name: "新闻纸")
c.children.create(name: "废报纸")
c.children.create(name: "其它")

d.children.create(name: "橡胶颗粒")
d.children.create(name: "轮胎")
d.children.create(name: "旧衣服")
d.children.create(name: "牛仔裤")
d.children.create(name: "碎玻璃")
d.children.create(name: "玻璃瓶")
d.children.create(name: "电池")
d.children.create(name: "线路板")
d.children.create(name: "其它")
end






if Category.first.nil?

puts "开始填充回收资源分类数据"
Category.delete_all
a = Category.create(:name => "废金属")
b = Category.create(:name => "废塑料")
c = Category.create(:name => "废电子电器")
d = Category.create(:name => "废橡胶")
f = Category.create(:name => "废纸")
g = Category.create(:name => "废皮革")
h = Category.create(:name => "废纺织品")
i = Category.create(:name => "废旧二手设备")
j = Category.create(:name => "废玻璃")
k = Category.create(:name => "其他废料")
l = Category.create(:name => "服务")

a_a = a.children.create(:name => "废钢铁")
a_b = a.children.create(:name => "有色金属")
a_c = a.children.create(:name => "稀有金属")
a_d = a.children.create(:name => "贵金属")
a_e = a.children.create(:name => "再生金属")
a_f = a.children.create(:name => "金属混合/复合料")
a_g = a.children.create(:name => "废金属处理设备")
a_h = a.children.create(:name => "硅")
a_i = a.children.create(:name => "金属助剂")

a_a_a = a_a.children.create(:name => "废铁")
a_a_a.children.create(:name => "生铁")
a_a_a.children.create(:name => "废铁轨")
a_a_a.children.create(:name => "不锈铁")
a_a_a.children.create(:name => "氧化铁")
a_a_a.children.create(:name => "熟铁")
a_a_a.children.create(:name => "铁矿")
a_a_a.children.create(:name => "磁铁")
a_a_a.children.create(:name => "铁合金")
a_a_a.children.create(:name => "废铁")
a_a_a.children.create(:name => "铁灰")
a_a_a.children.create(:name => "铁泥")
a_a_a.children.create(:name => "铁皮")
a_a_a.children.create(:name => "铁块")
a_a_a.children.create(:name => "铁粉")
a_a_a.children.create(:name => "铁屑")
a_a_a.children.create(:name => "铁渣")
a_a_a.children.create(:name => "铁边角料")
a_a_a.children.create(:name => "铁板")
a_a_a.children.create(:name => "铁线")
a_a_a.children.create(:name => "铁沙")
a_a_a.children.create(:name => "铁丝")

a_a_b = a_a.children.create(:name => "废钢")
a_a_b.children.create(:name => "不锈钢")
a_a_b.children.create(:name => "工具钢")
a_a_b.children.create(:name => "废钢轨/HMS")
a_a_b.children.create(:name => "钢丝")
a_a_b.children.create(:name => "矽钢")
a_a_b.children.create(:name => "钢板")
a_a_b.children.create(:name => "钢管")
a_a_b.children.create(:name => "钨钢")
a_a_b.children.create(:name => "钢渣")
a_a_b.children.create(:name => "冷轧钢")
a_a_b.children.create(:name => "钢筋")
a_a_b.children.create(:name => "钢制品")
a_a_b.children.create(:name => "特种钢")
a_a_b.children.create(:name => "热轧钢")
a_a_b.children.create(:name => "钢边角料")

a_a_c = a_a.children.create(:name => "废钢铁")
a_a_c.children.create(:name => "废钢铁")

a_b_a = a_b.children.create(:name => "废铜")
a_b_a.children.create(:name => "废铜") 
a_b_a.children.create(:name => "铜制品") 
a_b_a.children.create(:name => "铜材") 
a_b_a.children.create(:name => "黄杂铜") 
a_b_a.children.create(:name => "光亮铜") 
a_b_a.children.create(:name => "紫铜") 
a_b_a.children.create(:name => "铜矿") 
a_b_a.children.create(:name => "马达铜") 
a_b_a.children.create(:name => "海绵铜") 
a_b_a.children.create(:name => "铜合金") 
a_b_a.children.create(:name => "氧化铜") 
a_b_a.children.create(:name => "水箱铜") 
a_b_a.children.create(:name => "硫酸铜") 
a_b_a.children.create(:name => "铜粉") 
a_b_a.children.create(:name => "铜灰") 
a_b_a.children.create(:name => "铜屑") 
a_b_a.children.create(:name => "铜块") 
a_b_a.children.create(:name => "铜渣") 
a_b_a.children.create(:name => "铜泥") 
a_b_a.children.create(:name => "铜球") 
a_b_a.children.create(:name => "铜线") 
a_b_a.children.create(:name => "铜丝") 
a_b_a.children.create(:name => "铜边角料") 
a_b_a.children.create(:name => "含铜废料") 

a_b_b = a_b.children.create(:name => "废铝")
a_b_b.children.create(:name => "铝矿")
a_b_b.children.create(:name => "废铝")
a_b_b.children.create(:name => "铝合金")
a_b_b.children.create(:name => "铝制品")
a_b_b.children.create(:name => "氧化铝")
a_b_b.children.create(:name => "含铝废料")
a_b_b.children.create(:name => "铝块")
a_b_b.children.create(:name => "铝粉")
a_b_b.children.create(:name => "铝灰")
a_b_b.children.create(:name => "铝渣")
a_b_b.children.create(:name => "铝边角料")
a_b_b.children.create(:name => "铝泥")
a_b_b.children.create(:name => "铝线")
a_b_b.children.create(:name => "铝丝")
a_b_b.children.create(:name => "铝板")
a_b_b.children.create(:name => "铝箔")
a_b_b.children.create(:name => "铝锭")
a_b_b.children.create(:name => "铝屑")

a_b_c = a_b.children.create(:name => "锡")
a_b_c.children.create(:name => "锡")
a_b_c.children.create(:name => "锡矿")
a_b_c.children.create(:name => "焊锡")
a_b_c.children.create(:name => "锡合金")
a_b_c.children.create(:name => "氧化锡")
a_b_c.children.create(:name => "锡膏")
a_b_c.children.create(:name => "锡线")
a_b_c.children.create(:name => "锡渣")
a_b_c.children.create(:name => "锡泥")
a_b_c.children.create(:name => "锡灰")
a_b_c.children.create(:name => "锡块")
a_b_c.children.create(:name => "锡粉")
a_b_c.children.create(:name => "锡纸")
a_b_c.children.create(:name => "锡丝")
a_b_c.children.create(:name => "含锡废料")

a_b_d = a_b.children.create(:name => "锰")
a_b_d.children.create(:name => "锰矿")
a_b_d.children.create(:name => "氧化锰")
a_b_d.children.create(:name => "锰合金")
a_b_d.children.create(:name => "锰")

a_b_e = a_b.children.create(:name => "铬")
a_b_e.children.create(:name => "氧化铬")
a_b_e.children.create(:name => "铬")

a_b_f = a_b.children.create(:name => "铅")
a_b_f.children.create(:name => "铅")
a_b_f.children.create(:name => "铅矿")
a_b_f.children.create(:name => "铅合金")
a_b_f.children.create(:name => "氧化铅")
a_b_f.children.create(:name => "含铅废料")
a_b_f.children.create(:name => "铅泥")
a_b_f.children.create(:name => "亚铅")

a_b_g = a_b.children.create(:name => "镁")
a_b_g.children.create(:name => "镁矿")
a_b_g.children.create(:name => "镁")
a_b_g.children.create(:name => "镁合金")
a_b_g.children.create(:name => "氧化镁")

a_b_h = a_b.children.create(:name => "镍")
a_b_h.children.create(:name => "废镍")
a_b_h.children.create(:name => "镍合金")
a_b_h.children.create(:name => "镍矿")
a_b_h.children.create(:name => "镍泥")
a_b_h.children.create(:name => "镍水")
a_b_h.children.create(:name => "镍粉")
a_b_h.children.create(:name => "镍边角料")
a_b_h.children.create(:name => "镍片")
a_b_h.children.create(:name => "镍板")
a_b_h.children.create(:name => "镍渣")
a_b_h.children.create(:name => "含镍废料")

a_b_i = a_b.children.create(:name => "锌")
a_b_i.children.create(:name => "废锌")
a_b_i.children.create(:name => "氧化锌")
a_b_i.children.create(:name => "锌合金")
a_b_i.children.create(:name => "锌矿")
a_b_i.children.create(:name => "含锌废料")
a_b_i.children.create(:name => "锌渣")
a_b_i.children.create(:name => "锌灰")
a_b_i.children.create(:name => "锌粉")
a_b_i.children.create(:name => "锌锭")
a_b_i.children.create(:name => "锌泥")

a_b_j = a_b.children.create(:name => "镉")
a_b_j.children.create(:name => "镉")
a_b_j.children.create(:name => "镉矿")
a_b_j.children.create(:name => "氧化镉")
a_b_j.children.create(:name => "镉合金")
a_b_j.children.create(:name => "海绵镉")
a_b_j.children.create(:name => "镉渣")
a_b_j.children.create(:name => "镉锭")
a_b_j.children.create(:name => "镉片")

a_b_k = a_b.children.create(:name => "锑")
a_b_k.children.create(:name => "锑合金")
a_b_k.children.create(:name => "锑矿")
a_b_k.children.create(:name => "锑")

a_b_l = a_b.children.create(:name => "钴")
a_b_l.children.create(:name => "钴")
a_b_l.children.create(:name => "钴合金")
a_b_l.children.create(:name => "氧化钴")
a_b_l.children.create(:name => "钴粉")
a_b_l.children.create(:name => "钴渣")
a_b_l.children.create(:name => "钴锭")
a_b_l.children.create(:name => "含钴废料")

a_b_m = a_b.children.create(:name => "其他有色金属")
a_b_m.children.create(:name => "其他有色金属")

a_c_a = a_c.children.create(:name => "钛") 
a_c_a.children.create(:name => "钛合金")
a_c_a.children.create(:name => "钛矿")
a_c_a.children.create(:name => "钛")
a_c_a.children.create(:name => "钛屑")
a_c_a.children.create(:name => "钛边角料")
a_c_a.children.create(:name => "钛板")
a_c_a.children.create(:name => "钛管")

a_c_b = a_c.children.create(:name => "锆") 
a_c_b.children.create(:name => "锆")
a_c_b.children.create(:name => "锆合金")
a_c_b.children.create(:name => "锆矿")
a_c_b.children.create(:name => "钢玉砖")
a_c_b.children.create(:name => "锆屑")
a_c_b.children.create(:name => "锆锭")
a_c_b.children.create(:name => "锆棒")
a_c_b.children.create(:name => "锆边角料")

a_c_c = a_c.children.create(:name => "钒") 
a_c_c.children.create(:name => "钒")
a_c_c.children.create(:name => "钒合金")
a_c_c.children.create(:name => "钒矿")
a_c_c.children.create(:name => "钒泥")
a_c_c.children.create(:name => "钒渣")

a_c_d = a_c.children.create(:name => "铌")
a_c_d.children.create(:name => "铌")
a_c_d.children.create(:name => "铌合金")
a_c_d.children.create(:name => "铌矿")
a_c_d.children.create(:name => "铌锭")
a_c_d.children.create(:name => "铌棒")
a_c_d.children.create(:name => "铌渣")
a_c_d.children.create(:name => "铌粉")

a_c_e = a_c.children.create(:name => "钽") 
a_c_e.children.create(:name => "钽")
a_c_e.children.create(:name => "钽矿")
a_c_e.children.create(:name => "钽丝")
a_c_e.children.create(:name => "钽块")

a_c_f = a_c.children.create(:name => "钼") 
a_c_f.children.create(:name => "钼合金")
a_c_f.children.create(:name => "钼矿")
a_c_f.children.create(:name => "钼")
a_c_f.children.create(:name => "钼丝")
a_c_f.children.create(:name => "钼粉")
a_c_f.children.create(:name => "含钼废料")

a_c_g = a_c.children.create(:name => "钨") 
a_c_g.children.create(:name => "钨")
a_c_g.children.create(:name => "钨合金")
a_c_g.children.create(:name => "钨粉")
a_c_g.children.create(:name => "钨条")
a_c_g.children.create(:name => "钨丝")

a_c_h = a_c.children.create(:name => "锂") 
a_c_h.children.create(:name => "锂")

a_c_i = a_c.children.create(:name => "铍") 
a_c_i.children.create(:name => "铍合金")
a_c_i.children.create(:name => "铍矿")
a_c_i.children.create(:name => "铍")

a_c_j = a_c.children.create(:name => "镓") 
a_c_j.children.create(:name => "镓")
a_c_j.children.create(:name => "镓合金")
a_c_j.children.create(:name => "镓锭")
a_c_j.children.create(:name => "镓粉")
a_c_j.children.create(:name => "镓管")
a_c_j.children.create(:name => "镓渣")

a_c_k = a_c.children.create(:name => "铟") 
a_c_k.children.create(:name => "铟矿")
a_c_k.children.create(:name => "铟合金")
a_c_k.children.create(:name => "铟")
a_c_k.children.create(:name => "铟锭")
a_c_k.children.create(:name => "铟粉")
a_c_k.children.create(:name => "铟渣")

a_c_l = a_c.children.create(:name => "铼") 
a_c_l.children.create(:name => "铼")
a_c_l.children.create(:name => "铼粉")

a_c_m = a_c.children.create(:name => "硒") 
a_c_m.children.create(:name => "硒")
a_c_m.children.create(:name => "硒粉")
a_c_m.children.create(:name => "硒鼓")

a_c_n = a_c.children.create(:name => "其他稀有金属") 
a_c_n.children.create(:name => "其他稀有金属")

a_d_a = a_d.children.create(:name => "金")
a_d_a.children.create(:name => "金")
a_d_a.children.create(:name => "金矿")
a_d_a.children.create(:name => "含金废料")
a_d_a.children.create(:name => "金块")

a_d_b = a_d.children.create(:name => "银")
a_d_b.children.create(:name => "银")
a_d_b.children.create(:name => "镀银")
a_d_b.children.create(:name => "含银废料")

a_d_c = a_d.children.create(:name => "钌")
a_d_c.children.create(:name => "钌")

a_d_d = a_d.children.create(:name => "铑")
a_d_d.children.create(:name => "铑")

a_d_e = a_d.children.create(:name => "钯")
a_d_e.children.create(:name => "钯")

a_d_f = a_d.children.create(:name => "锇")
a_d_f.children.create(:name => "锇")

a_d_g = a_d.children.create(:name => "铱")
a_d_g.children.create(:name => "铱")

a_d_h = a_d.children.create(:name => "铂")
a_d_h.children.create(:name => "铂")

a_d_i = a_d.children.create(:name => "废触媒")
a_d_i.children.create(:name => "废触媒")
a_d_i.children.create(:name => "催化剂")

a_e_a = a_e.children.create(:name => "再生铝")
a_e_a.children.create(:name => "再生铝")

a_e_b = a_e.children.create(:name => "再生铜")
a_e_b.children.create(:name => "再生铜")

a_e_c = a_e.children.create(:name => "再生铁")
a_e_c.children.create(:name => "再生铁")

a_e_d = a_e.children.create(:name => "再生镍")
a_e_d.children.create(:name => "再生镍")

a_e_e = a_e.children.create(:name => "再生锡")
a_e_e.children.create(:name => "再生锡")

a_e_f = a_e.children.create(:name => "再生铅")
a_e_f.children.create(:name => "再生铅")

a_e_g = a_e.children.create(:name => "再生锌")
a_e_g.children.create(:name => "再生锌")

a_e_h = a_e.children.create(:name => "其他再生金属")
a_e_h.children.create(:name => "其他再生金属")

a_f_a = a_f.children.create(:name => "废五金")

a_f_b = a_f.children.create(:name => "废变压器")
a_f_b.children.create(:name => "废变压器")

a_f_c = a_f.children.create(:name => "废马达(电机)")
a_f_c.children.create(:name => "废马达(电机)")

a_f_d = a_f.children.create(:name => "尾矿(矿石)")
a_f_d.children.create(:name => "尾矿(矿石)")

a_f_e = a_f.children.create(:name => "废液")
a_f_e.children.create(:name => "废液")

a_f_f = a_f.children.create(:name => "电线/电缆")
a_f_f.children.create(:name => "电线/电缆")

a_f_g = a_f.children.create(:name => "废电路板")
a_f_g.children.create(:name => "废电路板")

a_f_h = a_f.children.create(:name => "废线路板")
a_f_h.children.create(:name => "废线路板")

a_f_i = a_f.children.create(:name => "二级板")
a_f_i.children.create(:name => "二级板")

a_f_j = a_f.children.create(:name => "废轴承")
a_f_j.children.create(:name => "废轴承")

a_f_k = a_f.children.create(:name => "其他金属混合/复合料")
a_f_k.children.create(:name => "其他金属混合/复合料")

a_f_l = a_f.children.create(:name => "三元催化器")
a_f_l.children.create(:name => "三元催化器")

a_g_a = a_g.children.create(:name => "金属分离设备")
a_g_b = a_g.children.create(:name => "破碎/磨粉机")
a_g_c = a_g.children.create(:name => "金属打包机")
a_g_d = a_g.children.create(:name => "切削加工设备")
a_g_e = a_g.children.create(:name => "尾矿回收设备")
a_g_f = a_g.children.create(:name => "提炼设备")
a_g_g = a_g.children.create(:name => "金属成型设备")
a_g_h = a_g.children.create(:name => "焊接和粘接设备")
a_g_i = a_g.children.create(:name => "铜米机")
a_g_j = a_g.children.create(:name => "冲床/机车")
a_g_k = a_g.children.create(:name => "机床/车床")
a_g_l = a_g.children.create(:name => "其他废金属处理设备")

a_h_a = a_h.children.create(:name => "硅片")
a_h_b = a_h.children.create(:name => "单晶硅")
a_h_c = a_h.children.create(:name => "多晶硅")
a_h_d = a_h.children.create(:name => "氧化硅")

b_a = b.children.create(:name => "通用废塑料")
b_b = b.children.create(:name => "工程废塑料")
b_c = b.children.create(:name => "特种废塑料")
b_e = b.children.create(:name => "再生颗粒")
b_d = b.children.create(:name => "塑料混合/复合料")
b_f = b.children.create(:name => "塑料助剂")
b_g = b.children.create(:name => "废塑料处理设备")

b_a_a = b_a.children.create(:name => "PP")
b_a_a.children.create(:name => "PP")
b_a_a.children.create(:name => "PPN")
b_a_a.children.create(:name => "BOPP")
b_a_a.children.create(:name => "PPR")
b_a_a.children.create(:name => "PPC")
b_a_a.children.create(:name => "PP管")
b_a_a.children.create(:name => "PP膜")
b_a_a.children.create(:name => "PP边角料")
b_a_a.children.create(:name => "PP破碎料")
b_a_a.children.create(:name => "PP袋")
b_a_a.children.create(:name => "PP桶")
b_a_a.children.create(:name => "PP包")
b_a_a.children.create(:name => "PP瓶盖")
b_a_a.children.create(:name => "PP保险杆")
b_a_a.children.create(:name => "PP粉碎料")
b_a_a.children.create(:name => "PP打包带")
b_a_a.children.create(:name => "PP无纺布")

b_a_b = b_a.children.create(:name => "PE")
b_a_b.children.create(:name => "PE")
b_a_b.children.create(:name => "HDPE")
b_a_b.children.create(:name => "LDPE")
b_a_b.children.create(:name => "LLDPE")
b_a_b.children.create(:name => "PE膜")
b_a_b.children.create(:name => "PE边角料")
b_a_b.children.create(:name => "PE破碎料")
b_a_b.children.create(:name => "PE桶料")
b_a_b.children.create(:name => "PE胶纸")
b_a_b.children.create(:name => "PE粉碎料")
b_a_b.children.create(:name => "PE电缆皮")

b_a_c = b_a.children.create(:name => "PVC")
b_a_c.children.create(:name => "PVC")
b_a_c.children.create(:name => "PVC药板")
b_a_c.children.create(:name => "PVC破碎料")
b_a_c.children.create(:name => "PVC膜")
b_a_c.children.create(:name => "PVC胶纸")
b_a_c.children.create(:name => "发泡PVC")
b_a_c.children.create(:name => "PVC墙纸")
b_a_c.children.create(:name => "PVC软料")
b_a_c.children.create(:name => "PVC硬料")
b_a_c.children.create(:name => "PVC电缆皮")
b_a_c.children.create(:name => "PVC管料")
b_a_c.children.create(:name => "PVC鞋底")
b_a_c.children.create(:name => "PVC安全网")
b_a_c.children.create(:name => "PVC广告布")

b_a_d = b_a.children.create(:name => "PS")
b_a_d.children.create(:name => "PS")
b_a_d.children.create(:name => "HIPS")
b_a_d.children.create(:name => "EPS")
b_a_d.children.create(:name => "GPPS")
b_a_d.children.create(:name => "PS板")
b_a_d.children.create(:name => "PS边角料")
b_a_d.children.create(:name => "PS破碎料")
b_a_d.children.create(:name => "PS膜")
b_a_d.children.create(:name => "PS机壳料")

b_a_e = b_a.children.create(:name => "ABS")
b_a_e.children.create(:name => "ABS")
b_a_e.children.create(:name => "ABS机壳料")
b_a_e.children.create(:name => "ABS粉碎料")
b_a_e.children.create(:name => "ABS边角料")
b_a_e.children.create(:name => "电镀ABS")
b_a_e.children.create(:name => "阻燃ABS")
b_a_e.children.create(:name => "ABS水口料")
b_a_e.children.create(:name => "防火ABS")

b_a_f = b_a.children.create(:name => "EVA")
b_a_f.children.create(:name => "EVA")
b_a_f.children.create(:name => "EVA回料")
b_a_f.children.create(:name => "EVA树脂")
b_a_f.children.create(:name => "EVA边角料")
b_a_f.children.create(:name => "EVA膜")
b_a_f.children.create(:name => "EVA副牌料")
b_a_f.children.create(:name => "EVA鞋底")

b_b_a = b_b.children.create(:name => "PA")
b_b_a.children.create(:name => "PA")
b_b_a.children.create(:name => "PA66")
b_b_a.children.create(:name => "PA6")
b_b_a.children.create(:name => "PA9T")
b_b_a.children.create(:name => "PA6T")
b_b_a.children.create(:name => "PA膜")
b_b_a.children.create(:name => "增强PA")
b_b_a.children.create(:name => "阻燃PA")
b_b_a.children.create(:name => "PA废丝")
b_b_a.children.create(:name => "PA破碎料")
b_b_a.children.create(:name => "PA水口料")
b_b_a.children.create(:name => "PA胶头")
b_b_a.children.create(:name => "PA渔网")

b_b_b = b_b.children.create(:name => "PET")
b_b_b.children.create(:name => "PET")
b_b_b.children.create(:name => "PBT")
b_b_b.children.create(:name => "X光片")
b_b_b.children.create(:name => "旧菲林片")
b_b_b.children.create(:name => "医用胶片")
b_b_b.children.create(:name => "PEN")
b_b_b.children.create(:name => "PET卷筒膜")
b_b_b.children.create(:name => "PET扎装瓶")
b_b_b.children.create(:name => "PET镀铝膜")
b_b_b.children.create(:name => "PET瓶")
b_b_b.children.create(:name => "PET瓶片")
b_b_b.children.create(:name => "PET膜")
b_b_b.children.create(:name => "PET破碎料")
b_b_b.children.create(:name => "PET边角料")
b_b_b.children.create(:name => "PET胶片")
b_b_b.children.create(:name => "PET打包带")

b_b_c = b_b.children.create(:name => "POM")
b_b_c.children.create(:name => "POM")
b_b_c.children.create(:name => "POM边角料")
b_b_c.children.create(:name => "POM破碎料")
b_b_c.children.create(:name => "POM机头料")
b_b_c.children.create(:name => "POM水口料")
b_b_c.children.create(:name => "POM杂色")
b_b_c.children.create(:name => "POM本色")

b_b_d = b_b.children.create(:name => "PPO")
b_b_d.children.create(:name => "PPO")
b_b_d.children.create(:name => "PPE")
b_b_d.children.create(:name => "MPPO")
b_b_d.children.create(:name => "PPO边角料")
b_b_d.children.create(:name => "PPO破碎料")

b_b_e = b_b.children.create(:name => "PC")
b_b_e.children.create(:name => "PC")
b_b_e.children.create(:name => "废光盘")
b_b_e.children.create(:name => "PC边角料")
b_b_e.children.create(:name => "PC破碎料")
b_b_e.children.create(:name => "PC膜")
b_b_e.children.create(:name => "PC光盘")
b_b_e.children.create(:name => "PC眼镜料")

b_b_f = b_b.children.create(:name => "纤维素类")
b_b_f.children.create(:name => "CN")
b_b_f.children.create(:name => "CA")
b_b_f.children.create(:name => "EC")
b_b_f.children.create(:name => "纤维素类")

b_b_g = b_b.children.create(:name => "PVB")
b_b_g.children.create(:name => "PVB")
b_b_g.children.create(:name => "PVB树脂")
b_b_g.children.create(:name => "PVB胶片")
b_b_g.children.create(:name => "PVB膜")
b_b_g.children.create(:name => "PVB玻璃胶")
b_b_g.children.create(:name => "PVB边角料")
b_b_g.children.create(:name => "PVB破碎料")

b_b_h = b_b.children.create(:name => "TPU")
b_b_h.children.create(:name => "TPU")
b_b_h.children.create(:name => "TPU卷筒膜")
b_b_h.children.create(:name => "TPU副牌")
b_b_h.children.create(:name => "TPU膜")

b_b_i = b_b.children.create(:name => "AS")
b_b_i.children.create(:name => "AS")

b_b_j = b_b.children.create(:name => "K胶")
b_b_j.children.create(:name => "K胶")
b_b_j.children.create(:name => "透明K胶")
b_b_j.children.create(:name => "副牌K胶")

b_b_k = b_b.children.create(:name => "PMMA")
b_b_k.children.create(:name => "PMMA")
b_b_k.children.create(:name => "亚克力")
b_b_k.children.create(:name => "亚加力")
b_b_k.children.create(:name => "有机玻璃")
b_b_k.children.create(:name => "PMMA边角料")
b_b_k.children.create(:name => "PMMA板材")
b_b_k.children.create(:name => "PMMA破碎料")
b_b_k.children.create(:name => "PMMA粉")

b_b_l = b_b.children.create(:name => "PPS")
b_b_l.children.create(:name => "PPS")
b_b_l.children.create(:name => "PPS水口料")
b_b_l.children.create(:name => "PPS树脂")

b_b_m = b_b.children.create(:name => "PU")
b_b_m.children.create(:name => "PU")
b_b_m.children.create(:name => "海绵")
b_b_m.children.create(:name => "PU鞋底")
b_b_m.children.create(:name => "水性PU")
b_b_m.children.create(:name => "高温PU")

b_b_n = b_b.children.create(:name => "其他工程塑料")
b_b_n.children.create(:name => "其他工程塑料")

b_b_o = b_b.children.create(:name => "LCP")
b_b_o.children.create(:name => "LCP")

b_c_a = b_c.children.create(:name => "氟塑料类")
b_c_a.children.create(:name => "氟塑料类")
b_c_a.children.create(:name => "PTFE")
b_c_a.children.create(:name => "FEP")

b_c_b = b_c.children.create(:name => "有机硅塑料")
b_c_b.children.create(:name => "有机硅塑料")

b_c_c = b_c.children.create(:name => "增强塑料")
b_c_c.children.create(:name => "增强塑料")

b_c_d = b_c.children.create(:name => "泡沫塑料")
b_c_d.children.create(:name => "泡沫")

b_c_e = b_c.children.create(:name => "其他特种塑料")
b_c_e.children.create(:name => "其他特种塑料")

b_d_a = b_d.children.create(:name => "塑料合金")
b_d_a.children.create(:name => "塑料合金")

b_d_b = b_d.children.create(:name => "纸塑复合料")
b_d_b.children.create(:name => "纸塑复合料")

b_d_c = b_d.children.create(:name => "金属塑料复合料")
b_d_c.children.create(:name => "金属塑料复合料")
b_d_c.children.create(:name => "PAP")

b_d_d = b_d.children.create(:name => "废渔网")
b_d_d.children.create(:name => "废渔网")

b_d_e = b_d.children.create(:name => "玻璃胶")
b_d_e.children.create(:name => "玻璃胶")
b_d_e.children.create(:name => "带纸玻璃胶")
b_d_e.children.create(:name => "不带纸玻璃胶")

b_d_f = b_d.children.create(:name => "牙膏皮")
b_d_f.children.create(:name => "牙膏皮")

b_d_g = b_d.children.create(:name => "电线/电缆皮")
b_d_g.children.create(:name => "电线/电缆皮")

b_d_h = b_d.children.create(:name => "塑料复合膜")

b_d_i = b_d.children.create(:name => "塑料混合")

b_e_a = b_e.children.create(:name => "PP再生颗粒")
b_e_a.children.create(:name => "PP一级料")
b_e_a.children.create(:name => "PP二级料")
b_e_a.children.create(:name => "PP三级料")
b_e_a.children.create(:name => "PP再生颗粒")
b_e_a.children.create(:name => "白色PP颗粒")
b_e_a.children.create(:name => "蓝色PP颗粒")
b_e_a.children.create(:name => "绿色PP颗粒")
b_e_a.children.create(:name => "黄色PP颗粒")
b_e_a.children.create(:name => "红色PP颗粒")
b_e_a.children.create(:name => "灰色PP颗粒")
b_e_a.children.create(:name => "黑色PP颗粒")
b_e_a.children.create(:name => "透明PP颗粒")

b_e_b = b_e.children.create(:name => "PE再生颗粒")
b_e_b.children.create(:name => "PE一级料")
b_e_b.children.create(:name => "PE二级料")
b_e_b.children.create(:name => "PE三级料")
b_e_b.children.create(:name => "PE再生颗粒")
b_e_b.children.create(:name => "白色PE颗粒")
b_e_b.children.create(:name => "蓝色PE颗粒")
b_e_b.children.create(:name => "绿色PE颗粒")
b_e_b.children.create(:name => "黄色PE颗粒")
b_e_b.children.create(:name => "红色PE颗粒")
b_e_b.children.create(:name => "灰色PE颗粒")
b_e_b.children.create(:name => "黑色PE颗粒")
b_e_b.children.create(:name => "透明PE颗粒")

b_e_c = b_e.children.create(:name => "PVC再生颗粒")
b_e_c.children.create(:name => "PVC一级料")
b_e_c.children.create(:name => "PVC二级料")
b_e_c.children.create(:name => "PVC三级料")
b_e_c.children.create(:name => "PVC再生颗粒")
b_e_c.children.create(:name => "白色PVC颗粒")
b_e_c.children.create(:name => "蓝色PVC颗粒")
b_e_c.children.create(:name => "绿色PVC颗粒")
b_e_c.children.create(:name => "黄色PVC颗粒")
b_e_c.children.create(:name => "红色PVC颗粒")
b_e_c.children.create(:name => "灰色PVC颗粒")
b_e_c.children.create(:name => "黑色PVC颗粒")
b_e_c.children.create(:name => "透明PVC颗粒")

b_e_d = b_e.children.create(:name => "ABS再生颗粒")
b_e_d.children.create(:name => "ABS一级料")
b_e_d.children.create(:name => "ABS二级料")
b_e_d.children.create(:name => "ABS三级料")
b_e_d.children.create(:name => "ABS再生颗粒")
b_e_d.children.create(:name => "白色ABS颗粒")
b_e_d.children.create(:name => "蓝色ABS颗粒")
b_e_d.children.create(:name => "绿色ABS颗粒")
b_e_d.children.create(:name => "黄色ABS颗粒")
b_e_d.children.create(:name => "红色ABS颗粒")
b_e_d.children.create(:name => "灰色ABS颗粒")
b_e_d.children.create(:name => "黑色ABS颗粒")
b_e_d.children.create(:name => "透明ABS颗粒")

b_e_e = b_e.children.create(:name => "PS再生颗粒")
b_e_e.children.create(:name => "PS一级料")
b_e_e.children.create(:name => "PS二级料")
b_e_e.children.create(:name => "PS三级料")
b_e_e.children.create(:name => "PS再生颗粒")
b_e_e.children.create(:name => "白色PS颗粒")
b_e_e.children.create(:name => "蓝色PS颗粒")
b_e_e.children.create(:name => "绿色PS颗粒")
b_e_e.children.create(:name => "黄色PS颗粒")
b_e_e.children.create(:name => "红色PS颗粒")
b_e_e.children.create(:name => "灰色PS颗粒")
b_e_e.children.create(:name => "黑色PS颗粒")
b_e_e.children.create(:name => "透明PS颗粒")

b_e_f = b_e.children.create(:name => "EVA再生颗粒")
b_e_f.children.create(:name => "EVA一级料")
b_e_f.children.create(:name => "EVA二级料")
b_e_f.children.create(:name => "EVA三级料")
b_e_f.children.create(:name => "EVA再生颗粒")
b_e_f.children.create(:name => "白色EVA颗粒")
b_e_f.children.create(:name => "蓝色EVA颗粒")
b_e_f.children.create(:name => "绿色EVA颗粒")
b_e_f.children.create(:name => "黄色EVA颗粒")
b_e_f.children.create(:name => "红色EVA颗粒")
b_e_f.children.create(:name => "灰色EVA颗粒")
b_e_f.children.create(:name => "黑色EVA颗粒")
b_e_f.children.create(:name => "透明EVA颗粒")

b_e_g = b_e.children.create(:name => "PA再生颗粒")
b_e_g.children.create(:name => "PA一级料")
b_e_g.children.create(:name => "PA二级料")
b_e_g.children.create(:name => "PA三级料")
b_e_g.children.create(:name => "PA再生颗粒")
b_e_g.children.create(:name => "白色PA颗粒")
b_e_g.children.create(:name => "蓝色PA颗粒")
b_e_g.children.create(:name => "绿色PA颗粒")
b_e_g.children.create(:name => "黄色PA颗粒")
b_e_g.children.create(:name => "红色PA颗粒")
b_e_g.children.create(:name => "灰色PA颗粒")
b_e_g.children.create(:name => "黑色PA颗粒")
b_e_g.children.create(:name => "透明PA颗粒")

b_e_h = b_e.children.create(:name => "PET再生颗粒")
b_e_h.children.create(:name => "PET一级料")
b_e_h.children.create(:name => "PET二级料")
b_e_h.children.create(:name => "PET三级料")
b_e_h.children.create(:name => "PET再生颗粒")
b_e_h.children.create(:name => "白色PET颗粒")
b_e_h.children.create(:name => "蓝色PET颗粒")
b_e_h.children.create(:name => "绿色PET颗粒")
b_e_h.children.create(:name => "黄色PET颗粒")
b_e_h.children.create(:name => "红色PET颗粒")
b_e_h.children.create(:name => "灰色PET颗粒")
b_e_h.children.create(:name => "黑色PET颗粒")
b_e_h.children.create(:name => "透明PET颗粒")

b_e_i = b_e.children.create(:name => "PPO再生颗粒")
b_e_i.children.create(:name => "PPO一级料")
b_e_i.children.create(:name => "PPO二级料")
b_e_i.children.create(:name => "PPO三级料")
b_e_i.children.create(:name => "PPO再生颗粒")
b_e_i.children.create(:name => "白色PPO颗粒")
b_e_i.children.create(:name => "蓝色PPO颗粒")
b_e_i.children.create(:name => "绿色PPO颗粒")
b_e_i.children.create(:name => "黄色PPO颗粒")
b_e_i.children.create(:name => "红色PPO颗粒")
b_e_i.children.create(:name => "灰色PPO颗粒")
b_e_i.children.create(:name => "黑色PPO颗粒")
b_e_i.children.create(:name => "透明PPO颗粒")

b_e_j = b_e.children.create(:name => "PC再生颗粒")
b_e_j.children.create(:name => "PC一级料")
b_e_j.children.create(:name => "PC二级料")
b_e_j.children.create(:name => "PC三级料")
b_e_j.children.create(:name => "PC再生颗粒")
b_e_j.children.create(:name => "白色PC颗粒")
b_e_j.children.create(:name => "蓝色PC颗粒")
b_e_j.children.create(:name => "绿色PC颗粒")
b_e_j.children.create(:name => "黄色PC颗粒")
b_e_j.children.create(:name => "红色PC颗粒")
b_e_j.children.create(:name => "灰色PC颗粒")
b_e_j.children.create(:name => "黑色PC颗粒")
b_e_j.children.create(:name => "透明PC颗粒")

b_e_k = b_e.children.create(:name => "其他再生颗粒")
b_e_k.children.create(:name => "其他再生颗粒")

b_f_a = b_f.children.create(:name => "色母剂")
b_f_a.children.create(:name => "色母剂")

b_f_b = b_f.children.create(:name => "增塑剂")
b_f_b.children.create(:name => "增塑剂")

b_f_c = b_f.children.create(:name => "催化剂")
b_f_c.children.create(:name => "催化剂")

b_f_d = b_f.children.create(:name => "增白剂")
b_f_d.children.create(:name => "增白剂")

b_f_e = b_f.children.create(:name => "润滑剂")
b_f_e.children.create(:name => "润滑剂")

b_f_g = b_f.children.create(:name => "改性剂")
b_f_g.children.create(:name => "改性剂")

b_f_h = b_f.children.create(:name => "阻燃剂")
b_f_h.children.create(:name => "阻燃剂")

b_f_i = b_f.children.create(:name => "光亮剂")
b_f_i.children.create(:name => "光亮剂")

b_f_j = b_f.children.create(:name => "着色剂")
b_f_j.children.create(:name => "着色剂")

b_f_k = b_f.children.create(:name => "粘合剂")
b_f_k.children.create(:name => "粘合剂")

b_f_l = b_f.children.create(:name => "其它助剂")

b_g_a = b_g.children.create(:name => "造粒机")
b_g_a.children.create(:name => "造粒机")
b_g_b = b_g.children.create(:name => "塑料分离设备")
b_g_b.children.create(:name => "塑料分离设备")
b_g_c = b_g.children.create(:name => "注塑机")
b_g_c.children.create(:name => "注塑机")
b_g_d = b_g.children.create(:name => "淋膜机")
b_g_d.children.create(:name => "淋膜机")
b_g_e = b_g.children.create(:name => "泡沫制造机")
b_g_e.children.create(:name => "泡沫制造机")
b_g_f = b_g.children.create(:name => "清洗设备")
b_g_f.children.create(:name => "清洗设备")
b_g_g = b_g.children.create(:name => "塑料破碎机")
b_g_g.children.create(:name => "塑料破碎机")
b_g_h = b_g.children.create(:name => "脱水机")
b_g_h.children.create(:name => "脱水机")
b_g_i = b_g.children.create(:name => "压力机")
b_g_i.children.create(:name => "压力机")
b_g_j = b_g.children.create(:name => "离心机")
b_g_j.children.create(:name => "离心机")
b_g_k = b_g.children.create(:name => "干燥机")
b_g_k.children.create(:name => "干燥机")
b_g_l = b_g.children.create(:name => "吹塑机/吹膜机")
b_g_l.children.create(:name => "吹塑机/吹膜机")
b_g_m = b_g.children.create(:name => "打包机")
b_g_m.children.create(:name => "打包机")
b_g_n = b_g.children.create(:name => "混合机")
b_g_n.children.create(:name => "混合机")
b_g_o = b_g.children.create(:name => "挤出机")
b_g_o.children.create(:name => "挤出机")
b_g_p = b_g.children.create(:name => "密炼机")
b_g_p.children.create(:name => "密炼机")
b_g_q = b_g.children.create(:name => "其他废塑料处理设备")
b_g_q.children.create(:name => "其他废塑料处理设备")

c_a = c.children.create(:name => "废电子")
c_b = c.children.create(:name => "废电器")
c_c = c.children.create(:name => "办公设备")

c_a_a = c_a.children.create(:name => "电路板")
c_a_a.children.create(:name => "电路板")
c_a_b = c_a.children.create(:name => "线路板")
c_a_b.children.create(:name => "线路板")
c_a_c = c_a.children.create(:name => "CPU")
c_a_c.children.create(:name => "CPU")
c_a_d = c_a.children.create(:name => "主板")
c_a_d.children.create(:name => "主板")
c_a_e = c_a.children.create(:name => "电容")
c_a_e.children.create(:name => "电容")
c_a_f = c_a.children.create(:name => "电池")
c_a_f.children.create(:name => "电池")
c_a_g = c_a.children.create(:name => "电瓶")
c_a_g.children.create(:name => "电瓶")
c_a_h = c_a.children.create(:name => "光驱(CD-R)")
c_a_h.children.create(:name => "光驱(CD-R)")
c_a_i = c_a.children.create(:name => "扬声器")
c_a_i.children.create(:name => "扬声器")
c_a_j = c_a.children.create(:name => "MOVP")
c_a_j.children.create(:name => "MOVP")
c_a_k = c_a.children.create(:name => "其他电子")
c_a_k.children.create(:name => "其他电子")
c_a_l = c_a.children.create(:name => "硬盘")
c_a_l.children.create(:name => "硬盘")
c_a_m = c_a.children.create(:name => "IC芯片")
c_a_m.children.create(:name => "IC芯片")
c_a_n = c_a.children.create(:name => "内存条")
c_a_n.children.create(:name => "内存条")

c_b_a = c_b.children.create(:name => "变压器")
c_b_a.children.create(:name => "变压器")
c_b_b = c_b.children.create(:name => "电源")
c_b_b.children.create(:name => "电源")
c_b_c = c_b.children.create(:name => "电表")
c_b_c.children.create(:name => "电表")
c_b_d = c_b.children.create(:name => "废电脑显示器")
c_b_d.children.create(:name => "废电脑显示器")
c_b_e = c_b.children.create(:name => "旧电脑")
c_b_e.children.create(:name => "旧电脑")
c_b_f = c_b.children.create(:name => "主机")
c_b_f.children.create(:name => "主机")
c_b_g = c_b.children.create(:name => "手机")
c_b_g.children.create(:name => "手机")
c_b_h = c_b.children.create(:name => "笔记本电脑")
c_b_h.children.create(:name => "笔记本电脑")
c_b_i = c_b.children.create(:name => "洗衣机")
c_b_i.children.create(:name => "洗衣机")
c_b_j = c_b.children.create(:name => "电视机")
c_b_j.children.create(:name => "电视机")
c_b_k = c_b.children.create(:name => "监视器")
c_b_k.children.create(:name => "监视器")
c_b_l = c_b.children.create(:name => "照相机")
c_b_l.children.create(:name => "照相机")
c_b_m = c_b.children.create(:name => "液晶屏(LCD)")
c_b_m.children.create(:name => "液晶屏(LCD)")
c_b_n = c_b.children.create(:name => "其他废电器")
c_b_n.children.create(:name => "其他废电器")

c_c_a = c_c.children.create(:name => "传真机")
c_c_a.children.create(:name => "传真机")
c_c_b = c_c.children.create(:name => "打印机")
c_c_b.children.create(:name => "打印机")
c_c_c = c_c.children.create(:name => "电话机")
c_c_c.children.create(:name => "电话机")
c_c_d = c_c.children.create(:name => "印刷机")
c_c_d.children.create(:name => "印刷机")
c_c_e = c_c.children.create(:name => "喷码机")
c_c_e.children.create(:name => "喷码机")
c_c_f = c_c.children.create(:name => "数据绘图仪")
c_c_f.children.create(:name => "数据绘图仪")
c_c_g = c_c.children.create(:name => "其他办公设备")
c_c_g.children.create(:name => "其他办公设备")
c_c_h = c_c.children.create(:name => "复印机")
c_c_h.children.create(:name => "复印机")

d_a = d.children.create(:name => "天然废橡胶")
d_b = d.children.create(:name => "合成橡胶")
d_c = d.children.create(:name => "热塑性弹性体")
d_d = d.children.create(:name => "再生胶")
d_e = d.children.create(:name => "废轮胎")
d_f = d.children.create(:name => "废橡胶处理设备")

d_a_a = d_a.children.create(:name => "乳胶")
d_a_a.children.create(:name => "乳胶")

d_a_b = d_a.children.create(:name => "天然橡胶")
d_a_b.children.create(:name => "天然橡胶")

d_b_a = d_b.children.create(:name => "硅橡胶")
d_b_a.children.create(:name => "硅橡胶")
d_b_b = d_b.children.create(:name => "氟橡胶")
d_b_b.children.create(:name => "氟橡胶")
d_b_c = d_b.children.create(:name => "丁苯橡胶(SBR)")
d_b_c.children.create(:name => "丁苯橡胶(SBR)")
d_b_d = d_b.children.create(:name => "顺丁橡胶(BR)")
d_b_d.children.create(:name => "顺丁橡胶(BR)")
d_b_e = d_b.children.create(:name => "氯丁橡胶(CR)")
d_b_e.children.create(:name => "氯丁橡胶(CR)")
d_b_f = d_b.children.create(:name => "乙丙橡胶")
d_b_f.children.create(:name => "乙丙橡胶")
d_b_g = d_b.children.create(:name => "丁腈橡胶(NBR)")
d_b_g.children.create(:name => "丁腈橡胶(NBR)")
d_b_h = d_b.children.create(:name => "聚硫橡胶")
d_b_h.children.create(:name => "聚硫橡胶")
d_b_i = d_b.children.create(:name => "丁基橡胶(IIR)")
d_b_i.children.create(:name => "丁基橡胶(IIR)")
d_b_j = d_b.children.create(:name => "丁晴橡胶(BNR)")
d_b_j.children.create(:name => "丁晴橡胶(BNR)")
d_b_k = d_b.children.create(:name => "未硫化橡胶(生胶)")
d_b_k.children.create(:name => "未硫化橡胶(生胶)")
d_b_l = d_b.children.create(:name => "其他合成橡胶")
d_b_l.children.create(:name => "其他合成橡胶")

d_d_a = d_d.children.create(:name => "胶鞋(鞋底)")
d_d_a.children.create(:name => "胶鞋(鞋底)")
d_d_b = d_d.children.create(:name => "橡胶粉")
d_d_b.children.create(:name => "橡胶粉")
d_d_c = d_d.children.create(:name => "橡胶颗粒")
d_d_c.children.create(:name => "橡胶颗粒")
d_d_d = d_d.children.create(:name => "橡胶破碎料")
d_d_d.children.create(:name => "橡胶破碎料")
d_d_e = d_d.children.create(:name => "其他再生胶")
d_d_e.children.create(:name => "其他再生胶")

d_e_a = d_e.children.create(:name => "内胎")
d_e_b = d_e.children.create(:name => "外胎")

d_f_a = d_f.children.create(:name => "橡胶处理油")
d_f_a.children.create(:name => "橡胶处理油")
d_f_b = d_f.children.create(:name => "切胶机")
d_f_b.children.create(:name => "切胶机")
d_f_c = d_f.children.create(:name => "打磨机")
d_f_c.children.create(:name => "打磨机")
d_f_d = d_f.children.create(:name => "橡胶挤出机")
d_f_d.children.create(:name => "橡胶挤出机")
d_f_e = d_f.children.create(:name => "密炼机")
d_f_e.children.create(:name => "密炼机")
d_f_f = d_f.children.create(:name => "剥皮机")
d_f_f.children.create(:name => "剥皮机")
d_f_g = d_f.children.create(:name => "开炼机")
d_f_g.children.create(:name => "开炼机")
d_f_h = d_f.children.create(:name => "硫化机")
d_f_h.children.create(:name => "硫化机")
d_f_i = d_f.children.create(:name => "成型机")
d_f_i.children.create(:name => "成型机")
d_f_j = d_f.children.create(:name => "贴合机/贴面机")
d_f_j.children.create(:name => "贴合机/贴面机")
d_f_k = d_f.children.create(:name => "橡胶造粒/粉碎机")
d_f_k.children.create(:name => "橡胶造粒/粉碎机")
d_f_l = d_f.children.create(:name => "制袋机")
d_f_l.children.create(:name => "制袋机")
d_f_m = d_f.children.create(:name => "炼油机/混炼机")
d_f_m.children.create(:name => "炼油机/混炼机")
d_f_n = d_f.children.create(:name => "分离设备")
d_f_n.children.create(:name => "分离设备")
d_f_o = d_f.children.create(:name => "胎缘切除机")
d_f_o.children.create(:name => "胎缘切除机")
d_f_p = d_f.children.create(:name => "其他废橡胶轮胎处理设备")
d_f_p.children.create(:name => "其他废橡胶轮胎处理设备")
d_f_q = d_f.children.create(:name => "轮胎翻新设备")
d_f_q.children.create(:name => "轮胎翻新设备")

f_a = f.children.create(:name => "美废")

f_b = f.children.create(:name => "欧废")

f_c = f.children.create(:name => "日废")

f_d = f.children.create(:name => "其他进口废纸")

f_e = f.children.create(:name => "包装废纸")
f_e_a = f_e.children.create(:name => "白板纸")
f_e_a.children.create(:name => "白板纸")
f_e_b = f_e.children.create(:name => "白卡纸")
f_e_b.children.create(:name => "白卡纸")
f_e_c = f_e.children.create(:name => "牛皮纸")
f_e_c.children.create(:name => "牛皮纸")
f_e_d = f_e.children.create(:name => "瓦楞纸")
f_e_d.children.create(:name => "瓦楞纸")
f_e_e = f_e.children.create(:name => "箱板纸")
f_e_e.children.create(:name => "箱板纸")
f_e_f = f_e.children.create(:name => "淋膜纸")
f_e_f.children.create(:name => "淋膜纸")
f_e_g = f_e.children.create(:name => "商标纸")
f_e_g.children.create(:name => "商标纸")
f_e_h = f_e.children.create(:name => "标签纸")
f_e_h.children.create(:name => "标签纸")
f_e_i = f_e.children.create(:name => "利乐包")
f_e_i.children.create(:name => "利乐包")
f_e_j = f_e.children.create(:name => "羊皮纸")
f_e_j.children.create(:name => "羊皮纸")
f_e_k = f_e.children.create(:name => "灰卡纸")
f_e_k.children.create(:name => "灰卡纸")
f_e_l = f_e.children.create(:name => "黄板纸")
f_e_l.children.create(:name => "黄板纸")
f_e_m = f_e.children.create(:name => "其他包装废纸")
f_e_m.children.create(:name => "其他包装废纸")
f_e_m.children.create(:name => "包装纸")

f_f = f.children.create(:name => "印刷废纸")
f_f_a = f_f.children.create(:name => "废报纸(ONP)")
f_f_a.children.create(:name => "废报纸(ONP)")
f_f_b = f_f.children.create(:name => "书刊")
f_f_b.children.create(:name => "书刊")
f_f_c = f_f.children.create(:name => "铜版纸")
f_f_c.children.create(:name => "铜版纸")
f_f_d = f_f.children.create(:name => "新闻纸")
f_f_d.children.create(:name => "新闻纸")
f_f_e = f_f.children.create(:name => "乱码纸")
f_f_e.children.create(:name => "乱码纸")
f_f_f = f_f.children.create(:name => "其他印刷废纸")
f_f_f.children.create(:name => "其他印刷废纸")
f_f_f.children.create(:name => "粉纸")

f_g = f.children.create(:name => "工业废纸")
f_g_a = f_g.children.create(:name => "工业废纸")
f_g_a.children.create(:name => "工业废纸")

f_h = f.children.create(:name => "办公废纸")
f_h_a = f_h.children.create(:name => "复写纸")
f_h_a.children.create(:name => "复写纸")
f_h_b = f_h.children.create(:name => "打印纸")
f_h_b.children.create(:name => "打印纸")
f_h_c = f_h.children.create(:name => "复印纸")
f_h_c.children.create(:name => "复印纸")
f_h_d = f_h.children.create(:name => "相纸")
f_h_d.children.create(:name => "相纸")
f_h_e = f_h.children.create(:name => "绵纸")
f_h_e.children.create(:name => "绵纸")
f_h_f = f_h.children.create(:name => "其他办公废纸")
f_h_f.children.create(:name => "其他办公废纸")

f_i = f.children.create(:name => "生活废纸")
f_i_a = f_i.children.create(:name => "卫生纸")
f_i_a.children.create(:name => "卫生纸")
f_i_b = f_i.children.create(:name => "面巾纸")
f_i_b.children.create(:name => "面巾纸")
f_i_c = f_i.children.create(:name => "餐巾纸")
f_i_c.children.create(:name => "餐巾纸")
f_i_d = f_i.children.create(:name => "纸尿裤")
f_i_d.children.create(:name => "纸尿裤")
f_i_e = f_i.children.create(:name => "卫生巾")
f_i_e.children.create(:name => "卫生巾")
f_i_f = f_i.children.create(:name => "湿巾纸")
f_i_f.children.create(:name => "湿巾纸")
f_i_g = f_i.children.create(:name => "其他生活废纸")
f_i_g.children.create(:name => "其他生活废纸")

f_j = f.children.create(:name => "特种废纸")
f_j_a = f_j.children.create(:name => "特种废纸")
f_j_a.children.create(:name => "特种废纸")
f_j_b = f_j.children.create(:name => "贴墙纸")
f_j_b.children.create(:name => "贴墙纸")

f_k = f.children.create(:name => "废纸制品")
f_k_a = f_k.children.create(:name => "纸箱")
f_k_a.children.create(:name => "纸箱")
f_k_b = f_k.children.create(:name => "纸盒(OCC)")
f_k_b.children.create(:name => "纸盒(OCC)")
f_k_c = f_k.children.create(:name => "纸板箱")
f_k_c.children.create(:name => "纸板箱")
f_k_d = f_k.children.create(:name => "其它纸制品")
f_k_d.children.create(:name => "其它纸制品")

f_l = f.children.create(:name => "纸浆")

f_m = f.children.create(:name => "卡纸")

f_n = f.children.create(:name => "纸边")

f_o = f.children.create(:name => "混合/复合废纸")
f_o_a = f_o.children.create(:name => "纸塑复合纸")
f_o_a.children.create(:name => "纸塑复合纸")
f_o_b = f_o.children.create(:name => "纸金属复合纸")
f_o_b.children.create(:name => "纸金属复合纸")

f_p = f.children.create(:name => "废纸处理设备")
f_p_a = f_p.children.create(:name => "废纸处理设备")
f_p_a.children.create(:name => "废纸处理设备")

g_a = g.children.create(:name => "人造皮革")
g_b = g.children.create(:name => "动物皮革")
g_c = g.children.create(:name => "皮料")
g_d = g.children.create(:name => "头层皮")
g_e = g.children.create(:name => "二层皮")

h_a = h.children.create(:name => "化纤")
h_a_a = h_a.children.create(:name => "合成化纤")
h_a_a.children.create(:name => "涤纶(PET)")
h_a_a.children.create(:name => "尼龙(PA)")
h_a_a.children.create(:name => "丙纶(PP)")
h_a_a.children.create(:name => "腈纶(丙烯)")
h_a_a.children.create(:name => "纤维")
h_a_a.children.create(:name => "锦纶")
h_a_a.children.create(:name => "氨纶")
h_a_a.children.create(:name => "芳纶")
h_a_a.children.create(:name => "维纶")

h_a_b = h_a.children.create(:name => "人造纤维")
h_a_b.children.create(:name => "人造纤维")

h_a_c = h_a.children.create(:name => "特种化纤")
h_a_c.children.create(:name => "特种化纤")

h_b = h.children.create(:name => "纱线")

h_c = h.children.create(:name => "坯布面料")
h_c_a = h_c.children.create(:name => "坯布")
h_c_a.children.create(:name => "坯布")
h_c_b = h_c.children.create(:name => "服装下脚料")
h_c_b.children.create(:name => "服装下脚料")
h_c_c = h_c.children.create(:name => "废布/碎布")
h_c_c.children.create(:name => "废布/碎布")
h_c_d = h_c.children.create(:name => "无纺布")
h_c_d.children.create(:name => "无纺布")
h_c_e = h_c.children.create(:name => "擦机布")
h_c_e.children.create(:name => "擦机布")
h_c_f = h_c.children.create(:name => "旧衣服")
h_c_f.children.create(:name => "旧衣服")
h_c_g = h_c.children.create(:name => "手套")
h_c_g.children.create(:name => "手套")

h_d = h.children.create(:name => "皮革")
h_d_a = h_d.children.create(:name => "人造皮革")
h_d_b = h_d.children.create(:name => "动物皮革")
h_d_c = h_d.children.create(:name => "皮料")
h_d_d = h_d.children.create(:name => "头层皮")
h_d_e = h_d.children.create(:name => "二层皮")

h_e = h.children.create(:name => "废棉料")
h_e_a = h_e.children.create(:name => "精硫落棉")
h_e_a.children.create(:name => "精硫落棉")
h_e_b = h_e.children.create(:name => "聚酯/脱脂棉")
h_e_b.children.create(:name => "聚酯/脱脂棉")
h_e_c = h_e.children.create(:name => "再生棉")
h_e_c.children.create(:name => "再生棉")
h_e_d = h_e.children.create(:name => "涤棉")
h_e_d.children.create(:name => "涤棉")
h_e_e = h_e.children.create(:name => "热风棉")
h_e_e.children.create(:name => "热风棉")
h_e_f = h_e.children.create(:name => "废棉料")
h_e_f.children.create(:name => "废棉料")

h_f = h.children.create(:name => "丝")
h_f_a = h_f.children.create(:name => "真丝")
h_f_a.children.create(:name => "真丝")
h_f_b = h_f.children.create(:name => "废丝")
h_f_b.children.create(:name => "废丝")

h_g = h.children.create(:name => "牛仔布")

h_h = h.children.create(:name => "家纺废料")
h_h_a = h_h.children.create(:name => "地毯料")
h_h_a.children.create(:name => "地毯料")
h_h_b = h_h.children.create(:name => "毛巾")
h_h_b.children.create(:name => "毛巾")

h_i = h.children.create(:name => "麻")
h_i_a = h_i.children.create(:name => "麻")
h_i_a.children.create(:name => "麻")
h_i_a.children.create(:name => "苎麻")
h_i_a.children.create(:name => "亚麻")

h_j = h.children.create(:name => "编织料")
h_j_a = h_j.children.create(:name => "编织料")
h_j_a.children.create(:name => "编织料")

h_k = h.children.create(:name => "纺织设备")

i_a = i.children.create(:name => "工程设备") 
i_a_a = i_a.children.create(:name => "起重机")
i_a_a.children.create(:name => "起重机")
i_a_b = i_a.children.create(:name => "沥青桶")
i_a_b.children.create(:name => "沥青桶")
i_a_c = i_a.children.create(:name => "抽水机")
i_a_c.children.create(:name => "抽水机")
i_a_d = i_a.children.create(:name => "挖土机")
i_a_d.children.create(:name => "挖土机")
i_a_e = i_a.children.create(:name => "推土机")
i_a_e.children.create(:name => "推土机")
i_a_f = i_a.children.create(:name => "其他工程设备")
i_a_f.children.create(:name => "其他工程设备")
i_a_g = i_a.children.create(:name => "挖掘机械")
i_a_h = i_a.children.create(:name => "装载机械")
i_a_i = i_a.children.create(:name => "搅拌机械")
i_a_j = i_a.children.create(:name => "焊接设备")
i_a_k = i_a.children.create(:name => "路面机械")
i_a_l = i_a.children.create(:name => "叉车")
i_a_m = i_a.children.create(:name => "海港吊")
i_a_n = i_a.children.create(:name => "履带吊")
i_a_o = i_a.children.create(:name => "汽车吊")
i_a_p = i_a.children.create(:name => "混凝土机械")
i_a_q = i_a.children.create(:name => "提升机")
i_a_r = i_a.children.create(:name => "工程车")
i_a_s = i_a.children.create(:name => "沥青搅拌机")
i_a_t = i_a.children.create(:name => "塔吊")
i_a_u = i_a.children.create(:name => "打桩机")
i_a_v = i_a.children.create(:name => "电焊条生产设备")
i_a_w = i_a.children.create(:name => "制砖机")
i_a_x = i_a.children.create(:name => "半挂车")

i_b = i.children.create(:name => "化工设备") 
i_b_a = i_b.children.create(:name => "清洗机")
i_b_a.children.create(:name => "清洗机")
i_b_b = i_b.children.create(:name => "挤压机")
i_b_b.children.create(:name => "挤压机")
i_b_c = i_b.children.create(:name => "撕碎机")
i_b_c.children.create(:name => "撕碎机")
i_b_d = i_b.children.create(:name => "离心机")
i_b_d.children.create(:name => "离心机")
i_b_e = i_b.children.create(:name => "炼焦机")
i_b_e.children.create(:name => "炼焦机")
i_b_f = i_b.children.create(:name => "电解槽")
i_b_f.children.create(:name => "电解槽")
i_b_g = i_b.children.create(:name => "反应釜")
i_b_g.children.create(:name => "反应釜")
i_b_h = i_b.children.create(:name => "磨碎机")
i_b_h.children.create(:name => "磨碎机")
i_b_i = i_b.children.create(:name => "旋窑")
i_b_i.children.create(:name => "旋窑")
i_b_j = i_b.children.create(:name => "制氧机")
i_b_j.children.create(:name => "制氧机")
i_b_k = i_b.children.create(:name => "热接收器")
i_b_k.children.create(:name => "热接收器")
i_b_l = i_b.children.create(:name => "储罐/贮罐")
i_b_l.children.create(:name => "储罐/贮罐")
i_b_m = i_b.children.create(:name => "其他化工设备")
i_b_m.children.create(:name => "其他化工设备")
i_b_n = i_b.children.create(:name => "储运设备")
i_b_o = i_b.children.create(:name => "反应设备")
i_b_p = i_b.children.create(:name => "实验设备")
i_b_q = i_b.children.create(:name => "混合设备")
i_b_r = i_b.children.create(:name => "成型设备")
i_b_s = i_b.children.create(:name => "粉碎设备")
i_b_t = i_b.children.create(:name => "化工装置")
i_b_u = i_b.children.create(:name => "肥料生产机械")
i_b_v = i_b.children.create(:name => "传质设备")
i_b_w = i_b.children.create(:name => "化工机械密封")
i_b_x = i_b.children.create(:name => "轮胎设备")
i_b_y = i_b.children.create(:name => "再生胶设备")
i_b_z = i_b.children.create(:name => "冷凝器")
i_b_aa = i_b.children.create(:name => "板框压滤机")
i_b_ab = i_b.children.create(:name => "液化气罐")
i_b_ac = i_b.children.create(:name => "硫化罐")
i_b_ad = i_b.children.create(:name => "氧气罐")
i_b_ae = i_b.children.create(:name => "蒸馏塔")
i_b_af = i_b.children.create(:name => "蒸馏水机")
i_b_ag = i_b.children.create(:name => "震荡筛")
i_b_ah = i_b.children.create(:name => "化工泵")
i_b_ai = i_b.children.create(:name => "烘箱")
i_b_aj = i_b.children.create(:name => "干燥机")
i_b_ak = i_b.children.create(:name => "玻璃设备")
i_b_al = i_b.children.create(:name => "橡胶设备")
i_b_am = i_b.children.create(:name => "制冷机")
i_b_an = i_b.children.create(:name => "传热设备")

i_c = i.children.create(:name => "制冷设备") 
i_c_a = i_c.children.create(:name => "制冷配件")
i_c_a.children.create(:name => "制冷配件")
i_c_b = i_c.children.create(:name => "制冷机")
i_c_b.children.create(:name => "制冷机")
i_c_c = i_c.children.create(:name => "空调")
i_c_c.children.create(:name => "空调")
i_c_d = i_c.children.create(:name => "压缩机")
i_c_d.children.create(:name => "压缩机")
i_c_e = i_c.children.create(:name => "其他制冷设备")
i_c_e.children.create(:name => "其他制冷设备")
i_c_f = i_c.children.create(:name => "蒸发器")
i_c_g = i_c.children.create(:name => "风冷热泵机组")
i_c_h = i_c.children.create(:name => "冷却塔")
i_c_i = i_c.children.create(:name => "冷库")
i_c_j = i_c.children.create(:name => "制冷机组")
i_c_k = i_c.children.create(:name => "其它未分类")

i_d = i.children.create(:name => "冶炼设备") 
i_d_a = i_d.children.create(:name => "锅炉")
i_d_a.children.create(:name => "锅炉")
i_d_b = i_d.children.create(:name => "转炉")
i_d_b.children.create(:name => "转炉")
i_d_c = i_d.children.create(:name => "压铸机")
i_d_c.children.create(:name => "压铸机")
i_d_d = i_d.children.create(:name => "油压机")
i_d_d.children.create(:name => "油压机")
i_d_e = i_d.children.create(:name => "轧管机")
i_d_e.children.create(:name => "轧管机")
i_d_f = i_d.children.create(:name => "冷轧机")
i_d_f.children.create(:name => "冷轧机")
i_d_g = i_d.children.create(:name => "其他冶炼设备")
i_d_g.children.create(:name => "其他冶炼设备")
i_d_h = i_d.children.create(:name => "冶金成套设备")
i_d_i = i_d.children.create(:name => "炼铁设备")
i_d_j = i_d.children.create(:name => "轧钢设备")
i_d_k = i_d.children.create(:name => "炼钢设备")
i_d_l = i_d.children.create(:name => "焦化设备")
i_d_m = i_d.children.create(:name => "液压设备")
i_d_n = i_d.children.create(:name => "高速轧制线")
i_d_o = i_d.children.create(:name => "烧结机")
i_d_p = i_d.children.create(:name => "铸钢厂设备")
i_d_q = i_d.children.create(:name => "电镀设备")
i_d_r = i_d.children.create(:name => "拉丝设备")
i_d_s = i_d.children.create(:name => "镀锡板生产线")
i_d_t = i_d.children.create(:name => "钢球设备")
i_d_u = i_d.children.create(:name => "钢带设备")
i_d_v = i_d.children.create(:name => "连铸机")
i_d_w = i_d.children.create(:name => "粉末冶金设备")
i_d_x = i_d.children.create(:name => "校平机")
i_d_y = i_d.children.create(:name => "铸造设备")
i_d_z = i_d.children.create(:name => "板金厂设备")
i_d_aa = i_d.children.create(:name => "热处理设备")
i_d_ab = i_d.children.create(:name => "不锈钢厂设备")
i_d_ac = i_d.children.create(:name => "钢管设备")
i_d_ad = i_d.children.create(:name => "钢丝设备")
i_d_ae = i_d.children.create(:name => "卷管机")
i_d_af = i_d.children.create(:name => "铝厂设备")
i_d_ag = i_d.children.create(:name => "轧机")
i_d_ah = i_d.children.create(:name => "无缝管设备")

i_e = i.children.create(:name => "交通工具") 
i_e_a = i_e.children.create(:name => "废旧汽车")
i_e_a.children.create(:name => "废旧汽车")
i_e_b = i_e.children.create(:name => "废旧摩托车")
i_e_b.children.create(:name => "废旧摩托车")
i_e_c = i_e.children.create(:name => "其他废旧交通工具")
i_e_c.children.create(:name => "其他废旧交通工具")
i_e_d = i_e.children.create(:name => "车辆修理设备")
i_e_e = i_e.children.create(:name => "火车")
i_e_f = i_e.children.create(:name => "各种汽车配件")
i_e_g = i_e.children.create(:name => "汽配加工设备")
i_e_h = i_e.children.create(:name => "飞机")
i_e_i = i_e.children.create(:name => "搬运设备")
i_e_j = i_e.children.create(:name => "堆垛机械")
i_e_k = i_e.children.create(:name => "其它未分类")

i_f = i.children.create(:name => "其他二手设备") 
i_f_a = i_f.children.create(:name => "其他二手设备") 
i_f_a.children.create(:name => "其他二手设备") 

i_g = i.children.create(:name => "二手商品") 
i_g_a = i_g.children.create(:name => "二手商品") 
i_g_a.children.create(:name => "二手商品") 

i_h = i.children.create(:name => "废塑料处理设备") 

i_i = i.children.create(:name => "废金属处理设备") 

i_j = i.children.create(:name => "废橡胶轮胎处理设备") 
i_j_a = i_j.children.create(:name => "炼胶机")

i_k = i.children.create(:name => "废纸处理设备") 

i_l = i.children.create(:name => "纺织设备") 
i_l_a = i_l.children.create(:name => "针织设备")
i_l_b = i_l.children.create(:name => "纺纱设备")
i_l_c = i_l.children.create(:name => "梭织设备")
i_l_d = i_l.children.create(:name => "其它未分类")
i_l_e = i_l.children.create(:name => "自动络筒机")
i_l_f = i_l.children.create(:name => "捻线机提花机")
i_l_g = i_l.children.create(:name => "卸料脱水机")
i_l_h = i_l.children.create(:name => "织带机编织机")
i_l_i = i_l.children.create(:name => "印染整套设备")
i_l_k = i_l.children.create(:name => "非织造布设备")
i_l_l = i_l.children.create(:name => "工业脱水机")
i_l_m = i_l.children.create(:name => "检针器检针机")
i_l_n = i_l.children.create(:name => "初加工设备")
i_l_o = i_l.children.create(:name => "喷气纺纱机")
i_l_p = i_l.children.create(:name => "绷网机印花机")
i_l_q = i_l.children.create(:name => "网眼经编机")
i_l_r = i_l.children.create(:name => "细纱机复合机")
i_l_s = i_l.children.create(:name => "多滚筒烫平机")
i_l_t = i_l.children.create(:name => "织绳机粗纱机")
i_l_u = i_l.children.create(:name => "筒子纱染色机")
i_l_v = i_l.children.create(:name => "烘干机植绒机")
i_l_w = i_l.children.create(:name => "纺丝机绣花机")
i_l_x = i_l.children.create(:name => "粘合机验布机")
i_l_y = i_l.children.create(:name => "无纺布设备")
i_l_z = i_l.children.create(:name => "织造机械")
i_l_aa = i_l.children.create(:name => "化纤机械")
i_l_ab = i_l.children.create(:name => "棉花加工设备")
i_l_ac = i_l.children.create(:name => "槽筒机")
i_l_ad = i_l.children.create(:name => "抓棉机")
i_l_ae = i_l.children.create(:name => "清钢联")
i_l_af = i_l.children.create(:name => "气流纺")
i_l_ag = i_l.children.create(:name => "精梳机")
i_l_ah = i_l.children.create(:name => "梳棉机")
i_l_ai = i_l.children.create(:name => "清花机")
i_l_aj = i_l.children.create(:name => "并条机")

i_m = i.children.create(:name => "电力电工设备") 
i_m_a = i_m.children.create(:name => "电站汽轮机")
i_m_b = i_m.children.create(:name => "燃气轮机")
i_m_c = i_m.children.create(:name => "水泵")
i_m_d = i_m.children.create(:name => "水轮机")
i_m_e = i_m.children.create(:name => "水轮发电机")
i_m_f = i_m.children.create(:name => "背压式汽轮机")
i_m_g = i_m.children.create(:name => "凝气式汽轮机")
i_m_h = i_m.children.create(:name => "控制开关柜")
i_m_i = i_m.children.create(:name => "电站锅炉")
i_m_j = i_m.children.create(:name => "变压设备")
i_m_k = i_m.children.create(:name => "输电设备")
i_m_l = i_m.children.create(:name => "其它未分类")
i_m_m = i_m.children.create(:name => "电工电气产品")
i_m_n = i_m.children.create(:name => "励磁机")
i_m_o = i_m.children.create(:name => "风力提水机")
i_m_p = i_m.children.create(:name => "太阳能发电机组")
i_m_q = i_m.children.create(:name => "电线电缆设备")
i_m_r = i_m.children.create(:name => "高低压成套开关")
i_m_s = i_m.children.create(:name => "变电站")
i_m_t = i_m.children.create(:name => "电源柜")
i_m_u = i_m.children.create(:name => "各类电站设备")
i_m_v = i_m.children.create(:name => "高压开关")
i_m_w = i_m.children.create(:name => "低压开关")
i_m_x = i_m.children.create(:name => "电流互感器")
i_m_y = i_m.children.create(:name => "电力电容器")
i_m_z = i_m.children.create(:name => "高压开关柜")
i_m_aa = i_m.children.create(:name => "直控开关及相关设备")

i_n = i.children.create(:name => "机床设备") 
i_n_a = i_n.children.create(:name => "抛光机")
i_n_b = i_n.children.create(:name => "拉床")
i_n_c = i_n.children.create(:name => "珩磨机")
i_n_d = i_n.children.create(:name => "冲床设备")
i_n_e = i_n.children.create(:name => "其它未分类")
i_n_f = i_n.children.create(:name => "钻床")
i_n_g = i_n.children.create(:name => "压力机")
i_n_h = i_n.children.create(:name => "折边,卷板设备")
i_n_i = i_n.children.create(:name => "剪切机床")
i_n_j = i_n.children.create(:name => "车床")
i_n_k = i_n.children.create(:name => "铣床")
i_n_l = i_n.children.create(:name => "镗床")
i_n_m = i_n.children.create(:name => "磨床")
i_n_n = i_n.children.create(:name => "锯床")
i_n_o = i_n.children.create(:name => "刨床")
i_n_p = i_n.children.create(:name => "轴承加工设备")
i_n_q = i_n.children.create(:name => "组合专机")
i_n_r = i_n.children.create(:name => "淬火/火花")
i_n_s = i_n.children.create(:name => "螺纹加工机床")
i_n_t = i_n.children.create(:name => "机床加工生产线")
i_n_u = i_n.children.create(:name => "插床")
i_n_v = i_n.children.create(:name => "加工中心")
i_n_w = i_n.children.create(:name => "线切割")
i_n_x = i_n.children.create(:name => "锻压机械")
i_n_y = i_n.children.create(:name => "数控机床")
i_n_z = i_n.children.create(:name => "齿轮加工机床")
i_n_aa = i_n.children.create(:name => "立车")
i_n_ab = i_n.children.create(:name => "弯管机")

i_o = i.children.create(:name => "石油设备") 
i_o_a = i_o.children.create(:name => "练化设备")
i_o_b = i_o.children.create(:name => "钻采设备")
i_o_c = i_o.children.create(:name => "储运设备")
i_o_d = i_o.children.create(:name => "其它未分类")
i_o_e = i_o.children.create(:name => "钻井设备")
i_o_f = i_o.children.create(:name => "采油设备")
i_o_g = i_o.children.create(:name => "修井设备")
i_o_h = i_o.children.create(:name => "固井设备")
i_o_i = i_o.children.create(:name => "炼油设备")
i_o_j = i_o.children.create(:name => "燃气设备")
i_o_k = i_o.children.create(:name => "储存设备")
i_o_l = i_o.children.create(:name => "润滑设备")
i_o_m = i_o.children.create(:name => "石油")

i_p = i.children.create(:name => "农业设备") 
i_p_a = i_p.children.create(:name => "粮油加工机械")
i_p_b = i_p.children.create(:name => "肥料加工机械")
i_p_c = i_p.children.create(:name => "饲料机械")
i_p_d = i_p.children.create(:name => "其它未分类")
i_p_e = i_p.children.create(:name => "土壤耕整机械")
i_p_f = i_p.children.create(:name => "食品加工设备")
i_p_g = i_p.children.create(:name => "无土栽培设备")
i_p_h = i_p.children.create(:name => "智能温室设备")
i_p_i = i_p.children.create(:name => "养殖设备")
i_p_j = i_p.children.create(:name => "方便面生产线")
i_p_k = i_p.children.create(:name => "收割机")
i_p_l = i_p.children.create(:name => "牧草打捆机")
i_p_m = i_p.children.create(:name => "饲料加工设备")
i_p_n = i_p.children.create(:name => "插秧机")
i_p_o = i_p.children.create(:name => "播种机")
i_p_p = i_p.children.create(:name => "大米加工设备")

i_q = i.children.create(:name => "压缩分离") 
i_q_a = i_q.children.create(:name => "气体分离设备")
i_q_b = i_q.children.create(:name => "过滤分离设备")
i_q_c = i_q.children.create(:name => "空压机")
i_q_d = i_q.children.create(:name => "压缩机")
i_q_e = i_q.children.create(:name => "潜孔钻")
i_q_f = i_q.children.create(:name => "离心压缩机")
i_q_g = i_q.children.create(:name => "其它未分类")

i_r = i.children.create(:name => "工业锅炉") 
i_r_a = i_r.children.create(:name => "锅炉")
i_r_b = i_r.children.create(:name => "燃气锅炉")
i_r_c = i_r.children.create(:name => "锅炉配件")
i_r_d = i_r.children.create(:name => "燃油锅炉")
i_r_e = i_r.children.create(:name => "链条锅炉")
i_r_f = i_r.children.create(:name => "蒸汽锅炉")
i_r_g = i_r.children.create(:name => "其它未分类锅炉")
i_r_h = i_r.children.create(:name => "燃煤热水锅炉")
i_r_i = i_r.children.create(:name => "电厂锅炉")
i_r_j = i_r.children.create(:name => "立式锅炉")
i_r_k = i_r.children.create(:name => "炉排锅炉")
i_r_l = i_r.children.create(:name => "卧式锅炉")
i_r_m = i_r.children.create(:name => "燃煤蒸汽锅炉")

i_s = i.children.create(:name => "印刷设备") 
i_s_a = i_s.children.create(:name => "印后加工设备")
i_s_b = i_s.children.create(:name => "排版设备")
i_s_c = i_s.children.create(:name => "印刷机械")
i_s_d = i_s.children.create(:name => "制版设备")
i_s_e = i_s.children.create(:name => "捆扎机")
i_s_f = i_s.children.create(:name => "上光机")
i_s_g = i_s.children.create(:name => "压痕机")
i_s_h = i_s.children.create(:name => "烫金机")
i_s_i = i_s.children.create(:name => "折页机")
i_s_j = i_s.children.create(:name => "复膜机")
i_s_k = i_s.children.create(:name => "压光机")
i_s_l = i_s.children.create(:name => "分切机")
i_s_m = i_s.children.create(:name => "喷码机")
i_s_n = i_s.children.create(:name => "复合机")
i_s_o = i_s.children.create(:name => "包本机")
i_s_p = i_s.children.create(:name => "晒版机")
i_s_q = i_s.children.create(:name => "进口印刷机")
i_s_r = i_s.children.create(:name => "切纸机")
i_s_s = i_s.children.create(:name => "烤版机")
i_s_t = i_s.children.create(:name => "印前系统")
i_s_u = i_s.children.create(:name => "印刷机械配件")
i_s_v = i_s.children.create(:name => "丝印机")
i_s_w = i_s.children.create(:name => "轮转印刷机")
i_s_x = i_s.children.create(:name => "双色胶印机")
i_s_y = i_s.children.create(:name => "单色胶印机")
i_s_z = i_s.children.create(:name => "不干胶（标签）印刷机")
i_s_aa = i_s.children.create(:name => "移印机")
i_s_ab = i_s.children.create(:name => "雕刻机")
i_s_ac = i_s.children.create(:name => "凹印机")
i_s_ad = i_s.children.create(:name => "多色胶印机")
i_s_ae = i_s.children.create(:name => "打码机")
i_s_af = i_s.children.create(:name => "柔印机")
i_s_ag = i_s.children.create(:name => "其它未分类")

i_t = i.children.create(:name => "包装设备") 
i_t_a = i_t.children.create(:name => "包装印刷加工")
i_t_b = i_t.children.create(:name => "复合材料包装设备")
i_t_c = i_t.children.create(:name => "布料包装设备")
i_t_d = i_t.children.create(:name => "包装相关设备")
i_t_e = i_t.children.create(:name => "玻璃包装设备")
i_t_f = i_t.children.create(:name => "竹木包装设备")
i_t_g = i_t.children.create(:name => "包装检测设备")
i_t_h = i_t.children.create(:name => "塑料包装设备")
i_t_i = i_t.children.create(:name => "其它未分类")
i_t_j = i_t.children.create(:name => "金属包装设备")
i_t_k = i_t.children.create(:name => "纸品包装设备")
i_t_l = i_t.children.create(:name => "喷码机")
i_t_m = i_t.children.create(:name => "贴标机械")
i_t_n = i_t.children.create(:name => "裹包机")
i_t_o = i_t.children.create(:name => "捆扎机械")
i_t_p = i_t.children.create(:name => "灌装机械")
i_t_q = i_t.children.create(:name => "打码机")
i_t_r = i_t.children.create(:name => "封口机")
i_t_s = i_t.children.create(:name => "充填机械")
i_t_t = i_t.children.create(:name => "绳索、扎带")
i_t_u = i_t.children.create(:name => "缠绕机")
i_t_v = i_t.children.create(:name => "打包机")

i_u = i.children.create(:name => "风机设备") 
i_u_a = i_u.children.create(:name => "矿井风机")
i_u_b = i_u.children.create(:name => "锅炉鼓引风机")
i_u_c = i_u.children.create(:name => "船用风机")
i_u_d = i_u.children.create(:name => "污水处理风机")
i_u_e = i_u.children.create(:name => "电站风机")
i_u_f = i_u.children.create(:name => "一般离心通风机")
i_u_g = i_u.children.create(:name => "一般轴流通风机")
i_u_h = i_u.children.create(:name => "屋顶风机")
i_u_i = i_u.children.create(:name => "离心鼓风机")
i_u_j = i_u.children.create(:name => "鼓引风机")
i_u_k = i_u.children.create(:name => "其他未分类风机")
i_u_l = i_u.children.create(:name => "罗茨鼓风机")
i_u_m = i_u.children.create(:name => "轴流通风机")
i_u_n = i_u.children.create(:name => "排尘风机")
i_u_o = i_u.children.create(:name => "烟草风机")
i_u_p = i_u.children.create(:name => "空调风机")
i_u_q = i_u.children.create(:name => "高温风机")
i_u_r = i_u.children.create(:name => "离心压缩机")

i_v = i.children.create(:name => "变速箱设备") 
i_v_a = i_v.children.create(:name => "变速器")
i_v_b = i_v.children.create(:name => "减速机")
i_v_c = i_v.children.create(:name => "其他未分类")
i_v_d = i_v.children.create(:name => "蜗轮螺杆升降机")
i_v_e = i_v.children.create(:name => "釜用立式减速机")
i_v_f = i_v.children.create(:name => "齿轮减速器")
i_v_g = i_v.children.create(:name => "蜗杆减速器")
i_v_h = i_v.children.create(:name => "联轴器、制动器与变速器")
i_v_i = i_v.children.create(:name => "行星齿轮减速器")
i_v_j = i_v.children.create(:name => "机械无级变速器")

i_w = i.children.create(:name => "矿业设备") 
i_w_a = i_w.children.create(:name => "采掘设备")
i_w_b = i_w.children.create(:name => "破碎设备")
i_w_c = i_w.children.create(:name => "选矿设备")
i_w_d = i_w.children.create(:name => "勘探设备")
i_w_e = i_w.children.create(:name => "安防设备")
i_w_f = i_w.children.create(:name => "其它未分类")
i_w_g = i_w.children.create(:name => "球磨机")
i_w_h = i_w.children.create(:name => "皮带机")
i_w_i = i_w.children.create(:name => "雷蒙磨")
i_w_j = i_w.children.create(:name => "烘干、干燥设备")

i_x = i.children.create(:name => "仪器仪表") 
i_x_a = i_x.children.create(:name => "仪器设备")
i_x_b = i_x.children.create(:name => "仪表")
i_x_c = i_x.children.create(:name => "光学仪器")
i_x_d = i_x.children.create(:name => "流量仪表")
i_x_e = i_x.children.create(:name => "电工仪器")
i_x_f = i_x.children.create(:name => "压力仪表")
i_x_g = i_x.children.create(:name => "温度仪表")
i_x_h = i_x.children.create(:name => "分析仪器")
i_x_i = i_x.children.create(:name => "实验仪器")
i_x_j = i_x.children.create(:name => "检测仪器")
i_x_k = i_x.children.create(:name => "其它未分类仪器")

i_y = i.children.create(:name => "发电机") 
i_y_a = i_y.children.create(:name => "其它发电机组")
i_y_b = i_y.children.create(:name => "水利发电设备")
i_y_c = i_y.children.create(:name => "其它未分类")
i_y_d = i_y.children.create(:name => "康明斯发电机(组)")
i_y_e = i_y.children.create(:name => "劳斯莱斯发电机(组)")
i_y_f = i_y.children.create(:name => "柴油发电机组")
i_y_g = i_y.children.create(:name => "汽油发电机组")
i_y_h = i_y.children.create(:name => "汽轮发电机组")
i_y_i = i_y.children.create(:name => "热力发电设备")
i_y_j = i_y.children.create(:name => "风力发电设备")

i_z = i.children.create(:name => "电动机") 
i_z_a = i_z.children.create(:name => "调速电机")
i_z_b = i_z.children.create(:name => "电机生产设备")
i_z_c = i_z.children.create(:name => "进口电动机")
i_z_d = i_z.children.create(:name => "直流电动机")
i_z_e = i_z.children.create(:name => "防爆电动机")
i_z_f = i_z.children.create(:name => "其它未分类电动机")
i_z_g = i_z.children.create(:name => "交流电动机")
i_z_h = i_z.children.create(:name => "轧钢电动机")

i_aa = i.children.create(:name => "备品备件") 
i_aa_a = i_aa.children.create(:name => "阀门")
i_aa_b = i_aa.children.create(:name => "轴承")
i_aa_c = i_aa.children.create(:name => "模具")
i_aa_d = i_aa.children.create(:name => "泵")
i_aa_e = i_aa.children.create(:name => "电动工具")
i_aa_f = i_aa.children.create(:name => "工具")
i_aa_g = i_aa.children.create(:name => "备件")
i_aa_h = i_aa.children.create(:name => "汽配")
i_aa_i = i_aa.children.create(:name => "刀具、夹具")
i_aa_j = i_aa.children.create(:name => "五金模具")
i_aa_k = i_aa.children.create(:name => "锻件")
i_aa_l = i_aa.children.create(:name => "铸件")
i_aa_m = i_aa.children.create(:name => "工程机械备件")
i_aa_n = i_aa.children.create(:name => "电力设备备件")
i_aa_o = i_aa.children.create(:name => "化工设备备件")
i_aa_p = i_aa.children.create(:name => "冶炼设备备件")
i_aa_q = i_aa.children.create(:name => "造纸设备备件")
i_aa_r = i_aa.children.create(:name => "塑料设备备件")
i_aa_s = i_aa.children.create(:name => "石油设备备件")
i_aa_t = i_aa.children.create(:name => "机床备件")
i_aa_u = i_aa.children.create(:name => "纺织设备备件")
i_aa_v = i_aa.children.create(:name => "风机备件")
i_aa_w = i_aa.children.create(:name => "印刷设备备件")
i_aa_x = i_aa.children.create(:name => "压缩设备备件")
i_aa_y = i_aa.children.create(:name => "锅炉备件")

i_ab = i.children.create(:name => "木工建材") 
i_ab_a = i_ab.children.create(:name => "木工机械")
i_ab_b = i_ab.children.create(:name => "铝塑板生产线")
i_ab_c = i_ab.children.create(:name => "石材设备")
i_ab_d = i_ab.children.create(:name => "frp板材生产线")
i_ab_e = i_ab.children.create(:name => "阳光板生产线")
i_ab_f = i_ab.children.create(:name => "玻璃钢设备")
i_ab_g = i_ab.children.create(:name => "彩钢板生产线")
i_ab_h = i_ab.children.create(:name => "地板生产线")
i_ab_i = i_ab.children.create(:name => "人造板生产线")
i_ab_j = i_ab.children.create(:name => "石膏板生产线")
i_ab_k = i_ab.children.create(:name => "胶合板生产线")
i_ab_l = i_ab.children.create(:name => "刨花板生产线")
i_ab_m = i_ab.children.create(:name => "型材设备")
i_ab_n = i_ab.children.create(:name => "铝合金板生产线")
i_ab_o = i_ab.children.create(:name => "门窗生产设备")
i_ab_p = i_ab.children.create(:name => "塑料管材设备")
i_ab_q = i_ab.children.create(:name => "不锈钢管设备")
i_ab_r = i_ab.children.create(:name => "波纹管生产线")
i_ab_s = i_ab.children.create(:name => "复合管设备")
i_ab_t = i_ab.children.create(:name => "镀锌卷板设备")
i_ab_u = i_ab.children.create(:name => "铝型材设备")
i_ab_v = i_ab.children.create(:name => "木工车床")
i_ab_w = i_ab.children.create(:name => "木工刨床")
i_ab_x = i_ab.children.create(:name => "塑胶地板生产线")
i_ab_y = i_ab.children.create(:name => "建筑幕墙设备")
i_ab_z = i_ab.children.create(:name => "木工锯床")
i_ab_aa = i_ab.children.create(:name => "木工开榫机")
i_ab_ab = i_ab.children.create(:name => "建筑施工设备")
i_ab_ac = i_ab.children.create(:name => "木材加工配套设备")
i_ab_ad = i_ab.children.create(:name => "各种制砖机械")

i_ac = i.children.create(:name => "食品设备") 
i_ac_a = i_ac.children.create(:name => "糖果设备")
i_ac_b = i_ac.children.create(:name => "制糖设备")
i_ac_c = i_ac.children.create(:name => "水产品加工设备")
i_ac_d = i_ac.children.create(:name => "淀粉设备")
i_ac_e = i_ac.children.create(:name => "面粉设备")
i_ac_f = i_ac.children.create(:name => "味精设备")
i_ac_g = i_ac.children.create(:name => "香料设备")
i_ac_h = i_ac.children.create(:name => "冰冻脱水蔬菜设备")
i_ac_i = i_ac.children.create(:name => "食品加工机械设备")
i_ac_j = i_ac.children.create(:name => "食醋设备")
i_ac_k = i_ac.children.create(:name => "酱油设备")
i_ac_l = i_ac.children.create(:name => "葡萄酒设备")
i_ac_m = i_ac.children.create(:name => "啤酒厂设备")
i_ac_n = i_ac.children.create(:name => "添加剂设备")
i_ac_o = i_ac.children.create(:name => "发酵设备")
i_ac_p = i_ac.children.create(:name => "卷烟设备")
i_ac_q = i_ac.children.create(:name => "酒厂设备")
i_ac_r = i_ac.children.create(:name => "鲜奶设备")
i_ac_s = i_ac.children.create(:name => "乳品厂设备")
i_ac_t = i_ac.children.create(:name => "屠宰设备")
i_ac_u = i_ac.children.create(:name => "肉制品加工设备")
i_ac_v = i_ac.children.create(:name => "鱿鱼加工设备")
i_ac_w = i_ac.children.create(:name => "薯片生产线")
i_ac_x = i_ac.children.create(:name => "果蔬处理设备")
i_ac_y = i_ac.children.create(:name => "饼干生产线")
i_ac_z = i_ac.children.create(:name => "保健食品设备")
i_ac_aa = i_ac.children.create(:name => "烘干设备")
i_ac_ab = i_ac.children.create(:name => "提取设备")
i_ac_ac = i_ac.children.create(:name => "食品包装设备")
i_ac_ad = i_ac.children.create(:name => "速冻食品设备")
i_ac_ae = i_ac.children.create(:name => "果酒设备")
i_ac_af = i_ac.children.create(:name => "罐头设备")
i_ac_ag = i_ac.children.create(:name => "果汁设备")
i_ac_ah = i_ac.children.create(:name => "果脯设备")
i_ac_ai = i_ac.children.create(:name => "超市设备")
i_ac_aj = i_ac.children.create(:name => "饮料生产设备")
i_ac_ak = i_ac.children.create(:name => "豆制品设备")
i_ac_al = i_ac.children.create(:name => "巧克力设备")
i_ac_am = i_ac.children.create(:name => "方便面生产线")
i_ac_an = i_ac.children.create(:name => "冰淇淋冷饮设备")
i_ac_ao = i_ac.children.create(:name => "其它食品机械")

i_ad = i.children.create(:name => "服装设备") 
i_ad_a = i_ad.children.create(:name => "洗涤设备")
i_ad_b = i_ad.children.create(:name => "裁剪设备")
i_ad_c = i_ad.children.create(:name => "切带机厚料机")
i_ad_d = i_ad.children.create(:name => "封包机特种机")
i_ad_e = i_ad.children.create(:name => "标签机削皮机")
i_ad_f = i_ad.children.create(:name => "包缝机曲折机")
i_ad_g = i_ad.children.create(:name => "花样机平缝机")
i_ad_h = i_ad.children.create(:name => "干洗设备烘干机")
i_ad_i = i_ad.children.create(:name => "家用机编织机")
i_ad_j = i_ad.children.create(:name => "卷线机摺景机")
i_ad_k = i_ad.children.create(:name => "链缝机包边机")
i_ad_l = i_ad.children.create(:name => "套结机刺绣机")
i_ad_m = i_ad.children.create(:name => "缝纫机压烫机")
i_ad_n = i_ad.children.create(:name => "熨烫设备")
i_ad_o = i_ad.children.create(:name => "粘合机绷缝机")
i_ad_p = i_ad.children.create(:name => "曲腕机开袋机")
i_ad_q = i_ad.children.create(:name => "花边机暗缝机")
i_ad_r = i_ad.children.create(:name => "珠边机毛皮机")
i_ad_s = i_ad.children.create(:name => "埋夹机钉扣机")
i_ad_t = i_ad.children.create(:name => "内衣织机")
i_ad_u = i_ad.children.create(:name => "其它未分类")
i_ad_v = i_ad.children.create(:name => "打孔机织补机")
i_ad_w = i_ad.children.create(:name => "织袜机")
i_ad_x = i_ad.children.create(:name => "水洗设备脱水机")
i_ad_y = i_ad.children.create(:name => "验布机预缩机")
i_ad_z = i_ad.children.create(:name => "摊布机裁布机")
i_ad_aa = i_ad.children.create(:name => "皮革加工设备")
i_ad_ab = i_ad.children.create(:name => "切條机高头车")
i_ad_ac = i_ad.children.create(:name => "制鞋设备")


i_ae = i.children.create(:name => "电子数码") 
i_ae_a = i_ae.children.create(:name => "数码摄像机")
i_ae_b = i_ae.children.create(:name => "数码相机")
i_ae_c = i_ae.children.create(:name => "手机")
i_ae_d = i_ae.children.create(:name => "电脑")
i_ae_e = i_ae.children.create(:name => "笔记本电脑")
i_ae_f = i_ae.children.create(:name => "电脑耗材")
i_ae_g = i_ae.children.create(:name => "电脑配件")
i_ae_h = i_ae.children.create(:name => "摄影设备")
i_ae_i = i_ae.children.create(:name => "音乐/影视/vcd/dvd")
i_ae_j = i_ae.children.create(:name => "家用电器")
i_ae_k = i_ae.children.create(:name => "办公设备")
i_ae_l = i_ae.children.create(:name => "掌上电脑")
i_ae_m = i_ae.children.create(:name => "贴片机")
i_ae_n = i_ae.children.create(:name => "其它电子设备")

i_af = i.children.create(:name => "变压器设备") 
i_af_a = i_af.children.create(:name => "隔离变压器")
i_af_b = i_af.children.create(:name => "变压器测试仪器")
i_af_c = i_af.children.create(:name => "其它未分类")
i_af_d = i_af.children.create(:name => "变压器附属机械")
i_af_e = i_af.children.create(:name => "低压变压器")
i_af_f = i_af.children.create(:name => "高频变压器")
i_af_g = i_af.children.create(:name => "三相变压器")
i_af_h = i_af.children.create(:name => "试验变压器")
i_af_i = i_af.children.create(:name => "控制变压器")
i_af_j = i_af.children.create(:name => "电子变压器")
i_af_k = i_af.children.create(:name => "自耦变压器")
i_af_l = i_af.children.create(:name => "特种变压器")
i_af_m = i_af.children.create(:name => "电源变压器")
i_af_n = i_af.children.create(:name => "配电变压器")
i_af_o = i_af.children.create(:name => "干式变压器")
i_af_p = i_af.children.create(:name => "高压变压器")
i_af_q = i_af.children.create(:name => "整流变压器")
i_af_r = i_af.children.create(:name => "散热器")
i_af_s = i_af.children.create(:name => "继电器")
i_af_t = i_af.children.create(:name => "电炉变压器")
i_af_u = i_af.children.create(:name => "电力变压器")

i_ag = i.children.create(:name => "行车设备") 
i_ag_a = i_ag.children.create(:name => "花架龙门吊")
i_ag_b = i_ag.children.create(:name => "单梁行车")
i_ag_c = i_ag.children.create(:name => "其它未分类")
i_ag_d = i_ag.children.create(:name => "冶金吊")
i_ag_e = i_ag.children.create(:name => "葫芦吊")
i_ag_f = i_ag.children.create(:name => "龙门吊")
i_ag_g = i_ag.children.create(:name => "双梁天车")
i_ag_h = i_ag.children.create(:name => "桥式行车")
i_ag_i = i_ag.children.create(:name => "双梁行车")

i_ah = i.children.create(:name => "注塑机设备") 
i_ah_a = i_ah.children.create(:name => "双色注塑机")
i_ah_b = i_ah.children.create(:name => "立式注塑机")
i_ah_c = i_ah.children.create(:name => "圆盘注塑机")
i_ah_d = i_ah.children.create(:name => "挤出机")
i_ah_e = i_ah.children.create(:name => "多色注塑机")
i_ah_f = i_ah.children.create(:name => "卧式注塑机")
i_ah_g = i_ah.children.create(:name => "其它未分类")
i_ah_h = i_ah.children.create(:name => "双螺杆注塑机")
i_ah_i = i_ah.children.create(:name => "单螺杆注塑机")
i_ah_j = i_ah.children.create(:name => "直压注塑机")

i_ai = i.children.create(:name => "船舶设备") 
i_ai_a = i_ai.children.create(:name => "锚机")
i_ai_b = i_ai.children.create(:name => "拖轮")
i_ai_c = i_ai.children.create(:name => "散货船")
i_ai_d = i_ai.children.create(:name => "冷藏船")
i_ai_e = i_ai.children.create(:name => "挖泥船")
i_ai_f = i_ai.children.create(:name => "起重船")
i_ai_g = i_ai.children.create(:name => "沙船")
i_ai_h = i_ai.children.create(:name => "多用途船")
i_ai_i = i_ai.children.create(:name => "集装箱船")
i_ai_j = i_ai.children.create(:name => "化学品船")
i_ai_k = i_ai.children.create(:name => "油船")
i_ai_l = i_ai.children.create(:name => "甲板驳")
i_ai_m = i_ai.children.create(:name => "浮吊船")
i_ai_n = i_ai.children.create(:name => "杂货船")
i_ai_o = i_ai.children.create(:name => "驳船")
i_ai_p = i_ai.children.create(:name => "客船")
i_ai_q = i_ai.children.create(:name => "渔船")
i_ai_r = i_ai.children.create(:name => "其它类船舶")
i_ai_s = i_ai.children.create(:name => "船舶配件")


i_aj = i.children.create(:name => "水泥设备") 
i_aj_a = i_aj.children.create(:name => "水泥罐车")
i_aj_b = i_aj.children.create(:name => "破碎机")
i_aj_c = i_aj.children.create(:name => "制砖机")
i_aj_d = i_aj.children.create(:name => "球磨机")
i_aj_e = i_aj.children.create(:name => "回转窑")
i_aj_f = i_aj.children.create(:name => "提升机")
i_aj_g = i_aj.children.create(:name => "搅拌车")
i_aj_h = i_aj.children.create(:name => "烘干机")
i_aj_i = i_aj.children.create(:name => "冷却机")
i_aj_j = i_aj.children.create(:name => "除尘设备")
i_aj_k = i_aj.children.create(:name => "燃烧器")
i_aj_l = i_aj.children.create(:name => "混凝土搅拌机")
i_aj_m = i_aj.children.create(:name => "包装机")
i_aj_n = i_aj.children.create(:name => "立磨")
i_aj_o = i_aj.children.create(:name => "计量设备")
i_aj_p = i_aj.children.create(:name => "输送机")
i_aj_q = i_aj.children.create(:name => "耐火材料")
i_aj_r = i_aj.children.create(:name => "篦冷机")
i_aj_s = i_aj.children.create(:name => "水泥生产线")
i_aj_t = i_aj.children.create(:name => "其它水泥设备")
i_aj_u = i_aj.children.create(:name => "机立窑")

i_ak = i.children.create(:name => "配件设备") 
i_ak_a = i_ak.children.create(:name => "电动工具")
i_ak_b = i_ak.children.create(:name => "汽配")
i_ak_c = i_ak.children.create(:name => "备件")
i_ak_d = i_ak.children.create(:name => "五金模具")
i_ak_e = i_ak.children.create(:name => "刀具、夹具")
i_ak_f = i_ak.children.create(:name => "阀门")
i_ak_g = i_ak.children.create(:name => "轴承")
i_ak_h = i_ak.children.create(:name => "模具")
i_ak_i = i_ak.children.create(:name => "工具")
i_ak_j = i_ak.children.create(:name => "泵")
i_ak_k = i_ak.children.create(:name => "风机备件")
i_ak_l = i_ak.children.create(:name => "印刷设备备件")
i_ak_m = i_ak.children.create(:name => "锅炉备件")
i_ak_n = i_ak.children.create(:name => "压缩设备备件")
i_ak_o = i_ak.children.create(:name => "造纸设备备件")
i_ak_p = i_ak.children.create(:name => "石油设备备件")
i_ak_q = i_ak.children.create(:name => "塑料设备备件")
i_ak_r = i_ak.children.create(:name => "机床备件")
i_ak_s = i_ak.children.create(:name => "工程机械备件")
i_ak_t = i_ak.children.create(:name => "电力设备备件")
i_ak_u = i_ak.children.create(:name => "冶炼设备备件")
i_ak_v = i_ak.children.create(:name => "纺织设备备件")
i_ak_w = i_ak.children.create(:name => "锻件")
i_ak_x = i_ak.children.create(:name => "铸件")
i_ak_y = i_ak.children.create(:name => "化工设备备件")

i_al = i.children.create(:name => "电梯设备") 
i_al_a = i_al.children.create(:name => "乘客电梯")
i_al_b = i_al.children.create(:name => "载货电梯")
i_al_c = i_al.children.create(:name => "医用电梯")
i_al_d = i_al.children.create(:name => "杂物电梯")
i_al_e = i_al.children.create(:name => "观光电梯")
i_al_f = i_al.children.create(:name => "船舶电梯")
i_al_g = i_al.children.create(:name => "车辆电梯")
i_al_h = i_al.children.create(:name => "其它未分类")
i_al_i = i_al.children.create(:name => "建筑施工电梯")
i_al_j = i_al.children.create(:name => "特种电梯")

i_am = i.children.create(:name => "陶瓷设备") 
i_am_a = i_am.children.create(:name => "其它未分类")
i_am_b = i_am.children.create(:name => "喷雾干燥塔")
i_am_c = i_am.children.create(:name => "成品修整设备")
i_am_d = i_am.children.create(:name => "干燥设备")
i_am_e = i_am.children.create(:name => "刮板分级机")
i_am_f = i_am.children.create(:name => "分散机")
i_am_g = i_am.children.create(:name => "高效磨剥机")
i_am_h = i_am.children.create(:name => "搅拌机")
i_am_i = i_am.children.create(:name => "陶瓷球阀")
i_am_j = i_am.children.create(:name => "捣浆机")
i_am_k = i_am.children.create(:name => "压滤机")
i_am_l = i_am.children.create(:name => "柱塞泵")
i_am_m = i_am.children.create(:name => "练泥机")
i_am_n = i_am.children.create(:name => "脱水设备")
i_am_o = i_am.children.create(:name => "给料设备")
i_am_p = i_am.children.create(:name => "筛分设备")
i_am_q = i_am.children.create(:name => "陶瓷窑炉")
i_am_r = i_am.children.create(:name => "球磨机")

i_an = i.children.create(:name => "通用设备") 
i_an_a = i_an.children.create(:name => "避孕套生产设备")
i_an_b = i_an.children.create(:name => "库存积压设备")
i_an_c = i_an.children.create(:name => "体育休闲设施")
i_an_d = i_an.children.create(:name => "安防设备")
i_an_e = i_an.children.create(:name => "电脑加工设备")
i_an_f = i_an.children.create(:name => "环保设备")
i_an_g = i_an.children.create(:name => "电脑及配件")
i_an_h = i_an.children.create(:name => "物流设备")
i_an_i = i_an.children.create(:name => "通信器材")
i_an_j = i_an.children.create(:name => "其它未分类设备")
i_an_k = i_an.children.create(:name => "游艺设备")
i_an_l = i_an.children.create(:name => "照明器材")
i_an_m = i_an.children.create(:name => "广电设备")
i_an_n = i_an.children.create(:name => "电器办公用品")
i_an_o = i_an.children.create(:name => "综合类信息")

i_ao = i.children.create(:name => "造纸设备") 
i_ao_a = i_ao.children.create(:name => "纸箱生产线")
i_ao_b = i_ao.children.create(:name => "瓦楞机")
i_ao_c = i_ao.children.create(:name => "长网造纸机")
i_ao_d = i_ao.children.create(:name => "漂白设备")
i_ao_e = i_ao.children.create(:name => "纸加工设备")
i_ao_f = i_ao.children.create(:name => "蒸煮设备")
i_ao_g = i_ao.children.create(:name => "碱回收设备")
i_ao_h = i_ao.children.create(:name => "切纸机")
i_ao_i = i_ao.children.create(:name => "纸杯机")
i_ao_j = i_ao.children.create(:name => "压光机")
i_ao_k = i_ao.children.create(:name => "单缸造纸机")
i_ao_l = i_ao.children.create(:name => "圆网纸机")
i_ao_m = i_ao.children.create(:name => "复卷机")
i_ao_n = i_ao.children.create(:name => "双缸造纸机")
i_ao_o = i_ao.children.create(:name => "其他未分类")
i_ao_p = i_ao.children.create(:name => "备料设备")
i_ao_q = i_ao.children.create(:name => "制浆设备")

i_ap = i.children.create(:name => "塑料设备") 
i_ap_a = i_ap.children.create(:name => "吹膜设备")
i_ap_b = i_ap.children.create(:name => "压延设备")
i_ap_c = i_ap.children.create(:name => "造粒设备")
i_ap_d = i_ap.children.create(:name => "成型设备")
i_ap_e = i_ap.children.create(:name => "塑料破碎机")
i_ap_f = i_ap.children.create(:name => "其他未分类")
i_ap_g = i_ap.children.create(:name => "吹瓶机")
i_ap_h = i_ap.children.create(:name => "制桶设备")
i_ap_i = i_ap.children.create(:name => "泡沫塑料生产线")
i_ap_j = i_ap.children.create(:name => "pvc管材生产设备")
i_ap_k = i_ap.children.create(:name => "型材生产线")
i_ap_l = i_ap.children.create(:name => "塑料编织设备")
i_ap_m = i_ap.children.create(:name => "制杯机")
i_ap_n = i_ap.children.create(:name => "挤出片材机")
i_ap_o = i_ap.children.create(:name => "分切机")
i_ap_p = i_ap.children.create(:name => "横切机")
i_ap_q = i_ap.children.create(:name => "淋膜机")
i_ap_r = i_ap.children.create(:name => "流延设备")

i_aq = i.children.create(:name => "橡胶设备") 
i_aq_a = i_aq.children.create(:name => "其它未分类")
i_aq_b = i_aq.children.create(:name => "切割机")
i_aq_c = i_aq.children.create(:name => "挤出机")
i_aq_d = i_aq.children.create(:name => "成型机")
i_aq_e = i_aq.children.create(:name => "磨边机")
i_aq_f = i_aq.children.create(:name => "密炼机")
i_aq_g = i_aq.children.create(:name => "开炼机")
i_aq_h = i_aq.children.create(:name => "硫化罐")
i_aq_i = i_aq.children.create(:name => "压延机")
i_aq_j = i_aq.children.create(:name => "破胶机")
i_aq_k = i_aq.children.create(:name => "裁断机")
i_aq_l = i_aq.children.create(:name => "硫化机")
i_aq_m = i_aq.children.create(:name => "炼胶机")

j_a = j.children.create(:name => "碎玻璃")

j_b = j.children.create(:name => "显像管玻璃")

j_c = j.children.create(:name => "玻璃纤维")
j_c_a = j_c.children.create(:name => "玻璃棉")
j_c_a.children.create(:name => "玻璃棉")
j_c_b = j_c.children.create(:name => "玻璃长纤维")
j_c_b.children.create(:name => "玻璃长纤维")
j_c_c = j_c.children.create(:name => "玻璃短纤维")
j_c_c.children.create(:name => "玻璃短纤维")

j_d = j.children.create(:name => "玻璃粉")
j_e = j.children.create(:name => "浮法玻璃")
j_f = j.children.create(:name => "平板玻璃")
j_g = j.children.create(:name => "玻璃瓶")
j_h = j.children.create(:name => "玻璃轧辊")
j_i = j.children.create(:name => "格法玻璃")
j_j = j.children.create(:name => "工业玻璃")

k_a = k.children.create(:name => "废木")
k_a_a = k_a.children.create(:name => "废木制品")
k_a_a.children.create(:name => "废木制品")
k_a_b = k_a.children.create(:name => "刨花/木削")
k_a_b.children.create(:name => "刨花/木削")
k_a_c = k_a.children.create(:name => "木屑/木粉")
k_a_c.children.create(:name => "木屑/木粉")

k_b = k.children.create(:name => "化工废料")
k_b_a = k_b.children.create(:name => "废硫")
k_b_a.children.create(:name => "废硫")
k_b_b = k_b.children.create(:name => "废碘")
k_b_b.children.create(:name => "废碘")
k_b_c = k_b.children.create(:name => "废油")
k_b_c.children.create(:name => "废油")
k_b_d = k_b.children.create(:name => "其他化工废料")
k_b_d.children.create(:name => "其他化工废料")

k_c = k.children.create(:name => "其他废料")
k_c_a = k_c.children.create(:name => "其他废料")
k_c_a.children.create(:name => "其他废料")

l_a = l.children.create(:name => "服务")
l_a_a = l_a.children.create(:name => "报关/清关服务")
l_a_a.children.create(:name => "报关/清关服务")
l_a_b = l_a.children.create(:name => "物流服务")
l_a_b.children.create(:name => "物流服务")
l_a_c = l_a.children.create(:name => "招聘")
l_a_c.children.create(:name => "招聘")
l_a_d = l_a.children.create(:name => "技术")
l_a_d.children.create(:name => "技术")
l_a_e = l_a.children.create(:name => "其他服务")
l_a_e.children.create(:name => "其他服务")
l_a_f = l_a.children.create(:name => "代理")
l_a_f.children.create(:name => "代理")
puts "填充回收资源数据完毕"

end
